### ISSUE TITLE
Menu bar icon is sometimes unresponsive

### ISSUE THREAD

**Issue by sfsam** [sfsam/Itsycal#1]
A handful of users have reported that the menu bar icon is occasionally unresponsive.

These reports have come from both OS X 10.10 and 10.11 systems. Some users seem to reliably see the issue when they restart their machines whereas others see it sporadically after waking their machines or connecting an external monitor.

I cannot replicate this bug on my machines and so am currently in the dark about the cause let alone a solution.

**Comment by mikem** [comment]
@sfsam I'm encountering this issue. Is there some way I can help you look into it?

**Comment by BenLeggieroNCR** [comment]
This seems to occur when Itsycal is killed off in the background but its icon is never removed. I fix it by opening Spotlight with Cmd-Space and typing Itsycal. Nothing opens, but the icon starts responding again, leading me to believe it really was just killed off.

**Comment by sfsam** [comment]
@mikem That would be great. Some questions: Can you describe exactly what you are experiencing? And can you reproduce the bug reliably? Are there any clues in your console log? I'm also wondering if Itsycal isn't playing nicely with some other software on the system that also runs during startup. It's odd that it seems to only affect some people and not others. I still can't reproduce it so I'm not sure where to begin.

**Comment by sfsam** [comment]
@BenLeggieroNCR When Itsycal is not responding, do you see it in the Activity Monitor?

**Comment by BenLeggieroNCR** [comment]
@sfsam I'll keep an eye out and comment here next time it happens.

**Comment by mikem** [comment]
@sfsam the symptoms are what @BenLeggieroNCR describes -- the icon remains in the menu bar, but clicking on it has no effect.

I haven't figured out exactly how to reproduce the issue. It's happened enough in the recent week or so that I began to look into it.

The next time I encounter this I'll take a look in the console log. If you have any suggestions for strings to search the log for, that'd be great, because chances are high I won't notice the issue immediately after it happens.

**Comment by sfsam** [comment]
@mikem I'd filter console messages on "Itsycal". If it happens when you start your machine, I'd look at all the console messages from when the machine booted.

**Comment by BenLeggieroNCR** [comment]
Caught it. This was all I saw in the log:

Console
---
```
2016-02-11 18:54:01.543 Itsycal[3728]: *** CFMessagePort: dropping corrupt reply Mach message (0b000100)
2016-02-12 09:27:33.114 SystemUIServer[549]: MenuCracker: Allowing "ItsycalExtra".
2016-02-12 09:27:44.179 Itsycal[758]: Menuextra is already loaded!
```
<img width="920" alt="screen shot 2016-02-12 at 09 56 43" src="https://cloud.githubusercontent.com/assets/10726457/13010272/049a9e5e-d16f-11e5-9bc7-4a50bf79d622.png">

Activity Monitor
---
<img width="815" alt="screen shot 2016-02-12 at 09 57 59" src="https://cloud.githubusercontent.com/assets/10726457/13010301/2df421e4-d16f-11e5-8c39-b48a68b16c69.png">

**Comment by sfsam** [comment]
So it looks like when Itsycal's icon is not responsive it hasn't been killed in the background since it is showing up in Activity Monitor. Is that right? And when you launch it from Spotlight to get it working again, do you end up with 2 Itsycal processes?
As for the console log, the last two messages are what you expect to see for the menu extra. I don't know what the CFMessagePort message means. I wonder if that is a clue.

**Comment by BenLeggieroNCR** [comment]
Nope, starting Itsycal from Spotlight fixes it and does _not_ create a duplicate process. Note that **in my previous comment's _CPU_ screenshot, it was using 0.0% CPU!** That that wasn't a momentary thing; it was actually stuck there. Below, we see it also at **0.0% before** starting Itsycal from Spotlight, but **1.6% after**.

# Activity Monitor
## CPU (Before)
0.0% CPU, 12 Threads, 0 Idle Wake Ups
<img width="815" alt="screen shot 2016-02-15 at 17 30 55" src="https://cloud.githubusercontent.com/assets/10726457/13062130/34fab118-d40a-11e5-9bf6-155c4d701425.png">

## CPU (After)
1.6% CPU, 13 Threads, 4 Idle Wake Ups
<img width="815" alt="screen shot 2016-02-15 at 17 31 05" src="https://cloud.githubusercontent.com/assets/10726457/13062132/3918da9a-d40a-11e5-88df-a30861b48d23.png">

**Comment by sfsam** [comment]
@BenLeggieroNCR For me, Itsycal almost always shows 0% CPU in Activity Monitor. It goes up a bit when I use it, but then goes down and idles at 0%. The CPU usage doesn't sound out of the ordinary.

**Comment by BenLeggieroNCR** [comment]
@sfsam well, you know more than I. All I can say is this is all I've seen. The Console, at the time of those screenshots, was blank.

**Comment by mikem** [comment]
I just encountered this issue again. There are two entries in the log:

```
2/18/16 11:52:08.459 launchservicesd[85]: Application App:"Itsycal" asn:0x0-6f06f0 pid:91838 refs=6 @ 0x7ff89f621ed0 tried to be brought forward, but isn't in fPermittedFrontApps ( ( "LSApplication:0x0-0xa12a12 pid=36525 "ScreenSaverEngine"", "LSApplication:0x0-0x1001 pid=103 "loginwindow"")), so denying. : LASSession.cp #1531 SetFrontApplication() q=LSSession 100008/0x186a8 queue
2/18/16 11:52:08.459 WindowServer[209]: [cps/setfront] Failed setting the front application to Itsycal, psn 0x0-0x6f06f0, securitySessionID=0x186a8, err=-13066
```

The process shows up in Activity Monitor, and appears to be doing something. After watching it for a little while I see the CPU utilization vary from 0% to 0.8%. I sampled the process, see below.

I also realized I can view old logs in Console by clicking on the "Earlier" button at the bottom. Here are some entries from the log from before the "crash" occurred (I can confirm the menu item still worked):

```
2/11/16 08:05:34.214 com.apple.xpc.launchd[1]: (com.mowglii.ItsycalApp.157152[45095]) Service exited due to signal: Terminated: 15
...
2/15/16 09:20:50.464 Itsycal[91838]: CoreData: warning: An NSManagedObjectContext delegate overrode fault handling behavior to silently delete the object with ID '0x7ff357005720 <x-coredata://67BA0F84-7075-4114-AF00-BC498F7E0159/Location/p2649>' and substitute nil/0 for all property values instead of throwing.
2/15/16 09:20:50.465 Itsycal[91838]: [com.apple.calendar.store.log.database] [Inaccessible fault: [<CalManagedLocation: 0x7ff3573e1810> (entity: Location; id: 0x7ff357005720 <x-coredata://67BA0F84-7075-4114-AF00-BC498F7E0159/Location/p2649> ; data: <fault>)] for objectID: [0x7ff357005720 <x-coredata://67BA0F84-7075-4114-AF00-BC498F7E0159/Location/p2649>]]
2/15/16 09:20:50.466 Itsycal[91838]: [com.apple.eventkit.log] [EventKit: Continuing despite inaccessible fault]
```

---

Here's the process sample output. I skipped the Binary Images section.

```
Sampling process 91838 for 3 seconds with 1 millisecond of run time between samples
Sampling completed, processing symbols...
Analysis of sampling Itsycal (pid 91838) every 1 millisecond
Process:         Itsycal [91838]
Path:            /opt/homebrew-cask/Caskroom/itsycal/0.10.8/Itsycal.app/Contents/MacOS/Itsycal
Load Address:    0x10fec4000
Identifier:      com.mowglii.ItsycalApp
Version:         0.10.9 (0.10.9)
Code Type:       X86-64
Parent Process:  ??? [1]

Date/Time:       2016-02-18 22:39:21.722 +0800
Launch Time:     2016-02-12 09:44:26.941 +0800
OS Version:      Mac OS X 10.11.3 (15D21)
Report Version:  7
Analysis Tool:   /usr/bin/sample
----

Call graph:
    2624 Thread_2162072   DispatchQueue_1: com.apple.main-thread  (serial)
    + 2624 start  (in libdyld.dylib) + 1  [0x7fff8ce6b5ad]
    +   2624 NSApplicationMain  (in AppKit) + 1176  [0x7fff9348b520]
    +     2624 -[NSApplication run]  (in AppKit) + 682  [0x7fff93508fc8]
    +       2624 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:]  (in AppKit) + 454  [0x7fff938df943]
    +         2624 _DPSNextEvent  (in AppKit) + 1067  [0x7fff935130ee]
    +           2624 _BlockUntilNextEventMatchingListInModeWithFilter  (in HIToolbox) + 71  [0x7fff8a8365af]
    +             2624 ReceiveNextEventCommon  (in HIToolbox) + 432  [0x7fff8a83676f]
    +               2624 RunCurrentEventLoopInMode  (in HIToolbox) + 235  [0x7fff8a836935]
    +                 2624 CFRunLoopRunSpecific  (in CoreFoundation) + 296  [0x7fff83a4b338]
    +                   2624 __CFRunLoopRun  (in CoreFoundation) + 1356  [0x7fff83a4baec]
    +                     2624 __CFRunLoopServiceMachPort  (in CoreFoundation) + 212  [0x7fff83a4c624]
    +                       2624 mach_msg  (in libsystem_kernel.dylib) + 55  [0x7fff877687c7]
    +                         2624 mach_msg_trap  (in libsystem_kernel.dylib) + 10  [0x7fff87769386]
    2624 Thread_2162075   DispatchQueue_2: com.apple.libdispatch-manager  (serial)
    + 2624 _dispatch_mgr_thread  (in libdispatch.dylib) + 52  [0x7fff887c6d01]
    +   2624 _dispatch_mgr_invoke  (in libdispatch.dylib) + 216  [0x7fff887c7099]
    +     2624 kevent_qos  (in libsystem_kernel.dylib) + 10  [0x7fff8776fff6]
    2624 Thread_2162154: com.apple.NSEventThread
    + 2624 thread_start  (in libsystem_pthread.dylib) + 13  [0x7fff8f72d375]
    +   2624 _pthread_start  (in libsystem_pthread.dylib) + 168  [0x7fff8f72fb90]
    +     2624 _pthread_body  (in libsystem_pthread.dylib) + 131  [0x7fff8f72fc13]
    +       2624 _NSEventThread  (in AppKit) + 149  [0x7fff935d2065]
    +         2624 CFRunLoopRunSpecific  (in CoreFoundation) + 296  [0x7fff83a4b338]
    +           2624 __CFRunLoopRun  (in CoreFoundation) + 1356  [0x7fff83a4baec]
    +             2624 __CFRunLoopServiceMachPort  (in CoreFoundation) + 212  [0x7fff83a4c624]
    +               2624 mach_msg  (in libsystem_kernel.dylib) + 55  [0x7fff877687c7]
    +                 2624 mach_msg_trap  (in libsystem_kernel.dylib) + 10  [0x7fff87769386]
    2624 Thread_2885818: com.apple.NSURLConnectionLoader
    + 2624 thread_start  (in libsystem_pthread.dylib) + 13  [0x7fff8f72d375]
    +   2624 _pthread_start  (in libsystem_pthread.dylib) + 168  [0x7fff8f72fb90]
    +     2624 _pthread_body  (in libsystem_pthread.dylib) + 131  [0x7fff8f72fc13]
    +       2624 __NSThread__start__  (in Foundation) + 1351  [0x7fff8a3c3c6f]
    +         2624 +[NSURLConnection(Loader) _resourceLoadLoop:]  (in CFNetwork) + 412  [0x7fff95ef86e9]
    +           2624 CFRunLoopRunSpecific  (in CoreFoundation) + 296  [0x7fff83a4b338]
    +             2624 __CFRunLoopRun  (in CoreFoundation) + 1356  [0x7fff83a4baec]
    +               2624 __CFRunLoopServiceMachPort  (in CoreFoundation) + 212  [0x7fff83a4c624]
    +                 2624 mach_msg  (in libsystem_kernel.dylib) + 55  [0x7fff877687c7]
    +                   2624 mach_msg_trap  (in libsystem_kernel.dylib) + 10  [0x7fff87769386]
    2624 Thread_2885829: com.apple.CFSocket.private
    + 2624 thread_start  (in libsystem_pthread.dylib) + 13  [0x7fff8f72d375]
    +   2624 _pthread_start  (in libsystem_pthread.dylib) + 168  [0x7fff8f72fb90]
    +     2624 _pthread_body  (in libsystem_pthread.dylib) + 131  [0x7fff8f72fc13]
    +       2624 __CFSocketManager  (in CoreFoundation) + 762  [0x7fff83a9816a]
    +         2624 __select  (in libsystem_kernel.dylib) + 10  [0x7fff8776f176]
    2624 Thread_2885840: JavaScriptCore::Marking
    + 2624 thread_start  (in libsystem_pthread.dylib) + 13  [0x7fff8f72d375]
    +   2624 _pthread_start  (in libsystem_pthread.dylib) + 168  [0x7fff8f72fb90]
    +     2624 _pthread_body  (in libsystem_pthread.dylib) + 131  [0x7fff8f72fc13]
    +       2624 WTF::wtfThreadEntryPoint(void*)  (in JavaScriptCore) + 15  [0x7fff86a5ac6f]
    +         2624 WTF::threadEntryPoint(void*)  (in JavaScriptCore) + 178  [0x7fff86a5ad42]
    +           2624 JSC::GCThread::gcThreadMain()  (in JavaScriptCore) + 88  [0x7fff86a653c8]
    +             2624 JSC::GCThread::waitForNextPhase()  (in JavaScriptCore) + 171  [0x7fff86a6557b]
    +               2624 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&)  (in libc++.1.dylib) + 47  [0x7fff8a19168f]
    +                 2624 _pthread_cond_wait  (in libsystem_pthread.dylib) + 767  [0x7fff8f730150]
    +                   2624 __psynch_cvwait  (in libsystem_kernel.dylib) + 10  [0x7fff8776eeb2]
    2624 Thread_2885841: JavaScriptCore::Marking
    + 2624 thread_start  (in libsystem_pthread.dylib) + 13  [0x7fff8f72d375]
    +   2624 _pthread_start  (in libsystem_pthread.dylib) + 168  [0x7fff8f72fb90]
    +     2624 _pthread_body  (in libsystem_pthread.dylib) + 131  [0x7fff8f72fc13]
    +       2624 WTF::wtfThreadEntryPoint(void*)  (in JavaScriptCore) + 15  [0x7fff86a5ac6f]
    +         2624 WTF::threadEntryPoint(void*)  (in JavaScriptCore) + 178  [0x7fff86a5ad42]
    +           2624 JSC::GCThread::gcThreadMain()  (in JavaScriptCore) + 88  [0x7fff86a653c8]
    +             2624 JSC::GCThread::waitForNextPhase()  (in JavaScriptCore) + 171  [0x7fff86a6557b]
    +               2624 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&)  (in libc++.1.dylib) + 47  [0x7fff8a19168f]
    +                 2624 _pthread_cond_wait  (in libsystem_pthread.dylib) + 767  [0x7fff8f730150]
    +                   2624 __psynch_cvwait  (in libsystem_kernel.dylib) + 10  [0x7fff8776eeb2]
    2624 Thread_2885842: JavaScriptCore::Marking
    + 2624 thread_start  (in libsystem_pthread.dylib) + 13  [0x7fff8f72d375]
    +   2624 _pthread_start  (in libsystem_pthread.dylib) + 168  [0x7fff8f72fb90]
    +     2624 _pthread_body  (in libsystem_pthread.dylib) + 131  [0x7fff8f72fc13]
    +       2624 WTF::wtfThreadEntryPoint(void*)  (in JavaScriptCore) + 15  [0x7fff86a5ac6f]
    +         2624 WTF::threadEntryPoint(void*)  (in JavaScriptCore) + 178  [0x7fff86a5ad42]
    +           2624 JSC::GCThread::gcThreadMain()  (in JavaScriptCore) + 88  [0x7fff86a653c8]
    +             2624 JSC::GCThread::waitForNextPhase()  (in JavaScriptCore) + 171  [0x7fff86a6557b]
    +               2624 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&)  (in libc++.1.dylib) + 47  [0x7fff8a19168f]
    +                 2624 _pthread_cond_wait  (in libsystem_pthread.dylib) + 767  [0x7fff8f730150]
    +                   2624 __psynch_cvwait  (in libsystem_kernel.dylib) + 10  [0x7fff8776eeb2]
    2624 Thread_2885843: JavaScriptCore::Marking
    + 2624 thread_start  (in libsystem_pthread.dylib) + 13  [0x7fff8f72d375]
    +   2624 _pthread_start  (in libsystem_pthread.dylib) + 168  [0x7fff8f72fb90]
    +     2624 _pthread_body  (in libsystem_pthread.dylib) + 131  [0x7fff8f72fc13]
    +       2624 WTF::wtfThreadEntryPoint(void*)  (in JavaScriptCore) + 15  [0x7fff86a5ac6f]
    +         2624 WTF::threadEntryPoint(void*)  (in JavaScriptCore) + 178  [0x7fff86a5ad42]
    +           2624 JSC::GCThread::gcThreadMain()  (in JavaScriptCore) + 88  [0x7fff86a653c8]
    +             2624 JSC::GCThread::waitForNextPhase()  (in JavaScriptCore) + 171  [0x7fff86a6557b]
    +               2624 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&)  (in libc++.1.dylib) + 47  [0x7fff8a19168f]
    +                 2624 _pthread_cond_wait  (in libsystem_pthread.dylib) + 767  [0x7fff8f730150]
    +                   2624 __psynch_cvwait  (in libsystem_kernel.dylib) + 10  [0x7fff8776eeb2]
    2624 Thread_2885844: JavaScriptCore::Marking
    + 2624 thread_start  (in libsystem_pthread.dylib) + 13  [0x7fff8f72d375]
    +   2624 _pthread_start  (in libsystem_pthread.dylib) + 168  [0x7fff8f72fb90]
    +     2624 _pthread_body  (in libsystem_pthread.dylib) + 131  [0x7fff8f72fc13]
    +       2624 WTF::wtfThreadEntryPoint(void*)  (in JavaScriptCore) + 15  [0x7fff86a5ac6f]
    +         2624 WTF::threadEntryPoint(void*)  (in JavaScriptCore) + 178  [0x7fff86a5ad42]
    +           2624 JSC::GCThread::gcThreadMain()  (in JavaScriptCore) + 88  [0x7fff86a653c8]
    +             2624 JSC::GCThread::waitForNextPhase()  (in JavaScriptCore) + 171  [0x7fff86a6557b]
    +               2624 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&)  (in libc++.1.dylib) + 47  [0x7fff8a19168f]
    +                 2624 _pthread_cond_wait  (in libsystem_pthread.dylib) + 767  [0x7fff8f730150]
    +                   2624 __psynch_cvwait  (in libsystem_kernel.dylib) + 10  [0x7fff8776eeb2]
    2624 Thread_2885845: JavaScriptCore::Marking
      2624 thread_start  (in libsystem_pthread.dylib) + 13  [0x7fff8f72d375]
        2624 _pthread_start  (in libsystem_pthread.dylib) + 168  [0x7fff8f72fb90]
          2624 _pthread_body  (in libsystem_pthread.dylib) + 131  [0x7fff8f72fc13]
            2624 WTF::wtfThreadEntryPoint(void*)  (in JavaScriptCore) + 15  [0x7fff86a5ac6f]
              2624 WTF::threadEntryPoint(void*)  (in JavaScriptCore) + 178  [0x7fff86a5ad42]
                2624 JSC::GCThread::gcThreadMain()  (in JavaScriptCore) + 88  [0x7fff86a653c8]
                  2624 JSC::GCThread::waitForNextPhase()  (in JavaScriptCore) + 171  [0x7fff86a6557b]
                    2624 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&)  (in libc++.1.dylib) + 47  [0x7fff8a19168f]
                      2624 _pthread_cond_wait  (in libsystem_pthread.dylib) + 767  [0x7fff8f730150]
                        2624 __psynch_cvwait  (in libsystem_kernel.dylib) + 10  [0x7fff8776eeb2]

Total number in stack (recursive counted multiple, when >=5):
        9       _pthread_body  (in libsystem_pthread.dylib) + 131  [0x7fff8f72fc13]
        9       _pthread_start  (in libsystem_pthread.dylib) + 168  [0x7fff8f72fb90]
        9       thread_start  (in libsystem_pthread.dylib) + 13  [0x7fff8f72d375]
        6       JSC::GCThread::gcThreadMain()  (in JavaScriptCore) + 88  [0x7fff86a653c8]
        6       JSC::GCThread::waitForNextPhase()  (in JavaScriptCore) + 171  [0x7fff86a6557b]
        6       WTF::threadEntryPoint(void*)  (in JavaScriptCore) + 178  [0x7fff86a5ad42]
        6       WTF::wtfThreadEntryPoint(void*)  (in JavaScriptCore) + 15  [0x7fff86a5ac6f]
        6       __psynch_cvwait  (in libsystem_kernel.dylib) + 0  [0x7fff8776eea8]
        6       _pthread_cond_wait  (in libsystem_pthread.dylib) + 767  [0x7fff8f730150]
        6       std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&)  (in libc++.1.dylib) + 47  [0x7fff8a19168f]

Sort by top of stack, same collapsed (when >= 5):
        __psynch_cvwait  (in libsystem_kernel.dylib)        15744
        mach_msg_trap  (in libsystem_kernel.dylib)        7872
        __select  (in libsystem_kernel.dylib)        2624
        kevent_qos  (in libsystem_kernel.dylib)        2624
```

**Comment by mikem** [comment]
Oh, I meant to add that I'll leave the process as is. If you'd like me to poke at it in its current state, let me know :-)

**Comment by sfsam** [comment]
@mikem When you just encountered the issue, what were the circumstances? Was it upon restarting your machine? I'll have to investigate the console messages you reported as I haven't seen those before. Do you have an idea of what they mean? I did find an issue with another app (SelfControl) with similar messages (https://github.com/SelfControlApp/selfcontrol/issues/164) but no resolution. As for the Core Data messages, I haven't seen those either. Itsycal doesn't use Core Data itself, but maybe the EventKit framework uses it under the hood.

**Comment by mikem** [comment]
@sfsam since the last time I launched Itsycal I either just close the lid on my MacBook or let it idle to sleep, multiple times a day. Itsycal lasted a few days of this before "crashing."

I use the [Padbury Clock screen saver](http://padbury.me/clock/) and I'm configured to require password immediately after sleep or screen saver begins in Security & Privacy settings. I wonder whether there's something going wrong when Itsycal tries to do something while the screensaver is running? Perhaps that's what the permission violations are about -- an app attempting to do something while the "screen is locked."

**Comment by sfsam** [comment]
@mikem Thanks for the info. So the issue appears to be triggered by sleeping/waking and/or starting/ending a screensaver. I've installed the clock screensaver and configured it the way you have yours to see if I can replicate the problem.

**Comment by mikem** [comment]
Itsycal has been running in its "crashed" state on my machine since it crashed 6 days ago. The date in the menu bar displays the correct date, but clicking on it doesn't display the popup.

I looked through the Console for any new Itsycal logs since the last ones I posted. Here they are:

```
2/23/16 14:09:35.590 Itsycal[91838]: CoreData: warning: An NSManagedObjectContext delegate overrode fault handling behavior to silently delete the object with ID '0x7ff3573c3280 <x-coredata://67BA0F84-7075-4114-AF00-BC498F7E0159/Location/p2669>' and substitute nil/0 for all property values instead of throwing.
2/23/16 14:09:35.591 Itsycal[91838]: [com.apple.calendar.store.log.database] [Inaccessible fault: [<CalManagedLocation: 0x7ff354660880> (entity: Location; id: 0x7ff3573c3280 <x-coredata://67BA0F84-7075-4114-AF00-BC498F7E0159/Location/p2669> ; data: <fault>)] for objectID: [0x7ff3573c3280 <x-coredata://67BA0F84-7075-4114-AF00-BC498F7E0159/Location/p2669>]]
2/23/16 14:09:35.591 Itsycal[91838]: [com.apple.eventkit.log] [EventKit: Continuing despite inaccessible fault]
```

Also, I tried re-launching Itsycal with Alfred and Spotlight as @BenLeggieroNCR [mentions above](https://github.com/sfsam/Itsycal/issues/1#issuecomment-182903694), but that doesn't work for me.

I also discovered that I'm running an older version, 0.10.9. A software update window popped up, though I told it to remind me later. I'll try upgrading next time I see it.

**Comment by Cromm** [comment]
I am also seeing this v0.10.12. App works perfectly until sleep then icon is non-clickable. I have just killed app in activity monitor and restarted it. I'll monitor what happens but let me know if I can post any info.

**Comment by bzx** [comment]
I am seeing this on v0.10.12 as well, and it has been like so since few versions of the app. I am on latest El Cap right now, but I am pretty sure I've definitely seen this issue happening on Mavericks.

It just happened to be unresponsive after system restart, but I didn't investigate the Activity Monitor and such. 

When I launch the Itsycal again, the issue is gone and I can trigger the calendar.

**Comment by naoyeye** [comment]
v0.10.12, +1

**Comment by marcogargano** [comment]
Hi, I had the same problem and I solved in this way.
In _System Preference > User & Groups > Login Items_, I removed the Hide flag for Itsycal and that's all.

Now for me, it's working well!!! :)

**Comment by naoyeye** [comment]
@marcogargano  thanks! so far so good. 👍

**Comment by Cromm** [comment]
Thank you @marcogargano. Working for me too.

**Comment by bzx** [comment]
@marcogargano thanks for the tip, WFM

**Comment by sfsam** [comment]
@marcogargano Thank you. I was finally able to replicate this issue by checking 'Hide' in the Login Items. If this is the solution for everyone who is seeing this issue, I am hugely relieved!

@bzx @Cromm @naoyeye I am curious how 'Hide' got checked for so many people in the first place. Is that something you manually checked or did it get checked automatically somehow?

**Comment by Cromm** [comment]
Sfsam I won't ever have touched this setting, so somehow it must have been set automatically. In my setup there are very few apps in this list that are checked (google, adoberesource, EOS utility). Basically, the things that you'd expect not to be shown. Very strange.

**Comment by bzx** [comment]
@sfsam I am deliberately checking "Hide" on all login items, just so that an app doesn't pop-up when I log in. I don't remember if I actually had an app installed that made me start doing it, or not... but it seems it's not necessary for all of the applications. 

The default checkbox state for newly added app is "unchecked".

**Comment by sfsam** [comment]
Well it looks like this issue has finally been solved so I'm closing it. Thanks again, @marcogargano.

**Comment by marcogargano** [comment]
Thank you for your great calendar app! ;-)
