### ISSUE TITLE
Add Active (Clicked Down) UI Mode?

### ISSUE THREAD

**Issue by chanjsq** [sfsam/Itsycal#106]
To have a better understand of I clicked down.

Something like:

![Normal Mode](https://user-images.githubusercontent.com/30150098/43367704-f9d824f8-9383-11e8-90e0-40191d7bb4e0.png)
![Active Mode](https://user-images.githubusercontent.com/30150098/43367705-fa22d228-9383-11e8-8c34-858667f23456.png)

**Comment by sfsam** [comment]
If you click, the calendar will appear so you know you clicked. Perhaps I don't understand what you mean?

**Comment by chanjsq** [comment]
![2018-08-28 8 13 30](https://user-images.githubusercontent.com/30150098/44693412-4a1e8600-aa9a-11e8-8837-df561f54460d.png)
I mean something like this, the blue background show its in active mode.
