### ISSUE TITLE
Wrong calendar displaying when using Buddhist calendar

### ISSUE THREAD

**Issue by earthpyy** [sfsam/Itsycal#108]
When using **Buddhist calendar** in macOS system preference
![image](https://user-images.githubusercontent.com/5132475/44089902-9a3ac7b4-9ff2-11e8-99ee-037a5b311e6e.png)

Year in calendar is showing correctly (in Buddhist year) but a calendar loaded data from Buddhist year (2561) which is not correct, because it should load from Gregorian year (2018).
<img width="175" alt="image" src="https://user-images.githubusercontent.com/5132475/44090170-7910b14c-9ff3-11e8-8399-954a1d6b51e7.png">

As you can see above, 14 Aug should be Tuesday not Friday.

The problem is solved if I changed **Calendar** in system preference to **Gregorian** and reopen application.

**Comment by sfsam** [comment]
Unfortunately, Itsycal only works properly with the Gregorian calendar. This is by design because it is the only calendar I can personally support.
