### ISSUE TITLE
White texte instead of black

### ISSUE THREAD

**Issue by mattvalle** [sfsam/Itsycal#116]
Hello there,
The date and time are written in white this morning.
<img width="191" alt="capture d ecran 2018-10-25 a 09 16 21" src="https://user-images.githubusercontent.com/9286071/47482406-c59c7980-d836-11e8-90f3-63fc9b335bdd.png">
Do you know where that comes from ?
Thanks for your help !
Matthieu

**Comment by sfsam** [comment]
@mattvalle Can you tell me about your setup? Can you reliably reproduce this behavior, and if so, can you tell me how? This should only occur if you are using the dark menu bar. In that case, it is something macOS does automatically.

**Comment by mattvalle** [comment]
My problem didn't come up this morning... It seems to be related to the light/dark menu feature of MacOS but doesn't seem to be a huge issue. I'd rather not bother you with it...
