### ISSUE TITLE
Installable with Homebrew

### ISSUE THREAD

**Issue by modestotech** [sfsam/Itsycal#121]
Hi 
Is this app available on Homebrew? I've found [this](https://github.com/Homebrew/homebrew-cask/issues/20886) old issue, but no I can't find it as a brew cask.

**Comment by seagle0128** [comment]
This should be closed. I installed it via brew cask.

**Comment by sfsam** [comment]
@seagle0128 I'm afraid I don't know anything about installing with Homebrew. If you could provide instructions on how you installed, I'd appreciate it. And then I could close this.

**Comment by seagle0128** [comment]
Sure. Refer to https://brew.sh/

```sh
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew cask install itsycal
```

**Comment by sfsam** [comment]
Thank you.
