### ISSUE TITLE
Use GitHub markdown for readme

### ISSUE THREAD

**Issue by co16353sidak** [sfsam/Itsycal#123]
Amazing tool and I have been using Itsycal for maybe a year or so.

One thing that I notice here is that the readme is using the `.txt` format whereas now GitHub supports `.md` files which allow for greater markdown capabilities.

I would love to submit a PR and create such a documentation for Itsycal.

**Comment by sfsam** [comment]
Thank you, I appreciate it. I'm going to leave it the way it is for now because the Readme is so simple and doesn't really need markdown.
