### ISSUE TITLE
Add support for rendering HTML in event descriptors

### ISSUE THREAD

**Issue by HarrisonB** [sfsam/Itsycal#126]
Right now, if an event has a description with HTML tags, they are rendered as plaintext.

I understand Itsycal is trying to be light and minimal--perhaps stripping HTML (other than anchor tags, as URLs already link out) would be an okay solution?

**Comment by sfsam** [comment]
Can you describe how to make such an event so I can look into this?

**Comment by HarrisonB** [comment]
If you create an event in Google Calendar, you have a WYSIWYG editor after clicking "More Options":

1. 
<img width="529" alt="image" src="https://user-images.githubusercontent.com/8454804/56476642-1ee50e80-6450-11e9-9000-77f84f81ebf8.png">

2. 
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/8454804/56476651-3d4b0a00-6450-11e9-80cc-a1572c165c4d.png">

**Comment by HarrisonB** [comment]
Looks like this was completed in c07e1fc6879f7a4671cf650649f9918f907a485d. Marking as closed! Thank you 😄

**Comment by sfsam** [comment]
It's far from perfect. I think it won't render bold or italic, but it will do lists and some other formatting. Importantly, it won't show raw HTML tags. Thank you for bringing this up.
