### ISSUE TITLE
Feature request: Option to show the time in menu bar icon

### ISSUE THREAD

**Issue by andr3wk** [sfsam/Itsycal#13]
Would love the option to show a digital clock as part of the menu bar icon. Personally because to get rid of Apple one and consolidate my menu bar.

Options:
- Show time in icon
  - Display the time with seconds
  - Use 24-hour clock
  - Show AM/PM

**Comment by rogeriomarques** [comment]
Yes! And if this option became available, an option to hide the calendar date - basically the same as the stock OSX clock or icon.

**Comment by grinser** [comment]
Oh yes - this would be the perfect Day-O replacement then.
I would suggest adding it in the flexible way Day-O provides, so everyone can choose how they want the day of week or time presented.

**Comment by jareha** [comment]
Being able to customize the format shown would be a welcome enhancement!

**Comment by pskowronek** [comment]
#25 - the pull request in there brings time option (w/o custom formatting, but this can be an enhancement to the enhancement :)). I have built the version with the patch and am using it right now - it is awesome! Check it out.

![itsycal-dayo](https://cloud.githubusercontent.com/assets/360665/20014448/4a2b6326-a2b7-11e6-971b-1a61be5894cb.png)

**Comment by sfsam** [comment]
@andr3wk @pskowronek @rogeriomarques @jareha I have been working on a new version that has a bunch of changes including a UI in Preferences for specifying the datetime pattern. You can try it and let me know what you think.

https://s3.amazonaws.com/itsycal/Itsycal-2017-01-21.zip

If you try it, please make sure it's the only version of Itsycal running on your system and make sure it is running from /Applications.

**Comment by andr3wk** [comment]
@sfsam Thanks but still on 10.11.6. Is it possible to continue supporting El Capitan?

**Comment by jareha** [comment]
Thanks @sfsam! I installed the version you provided a few hours ago, but, unfortunately, the app isn't showing up in the Mac menu bar.

(Followed your instructions there at the end too.)

**Comment by sfsam** [comment]
@jareha Oof, sorry. Could you try restarting your machine and see if that helps?

**Comment by rogeriomarques** [comment]
Thanks @sfsam but unfortunately I can't use Sierra for now. Do you really need the new APIs?

**Comment by jareha** [comment]
@sfsam Restarting was my first troubleshooting step, but will try again now!

**Comment by jareha** [comment]
It eventually loaded, so I guess the issue wasn’t the app, but my aging MacBook Pro! And your recent updates are perfect for my needs. You absolutely nailed every feature!

And, whoa! There’s even an option for a keyboard shortcut. All the exclamation marks!

**Comment by sfsam** [comment]
@jareha Can you elaborate on what slow loading/displaying means? When you moved the app to /Applications, did either of your computers prompt you for a password? Can you see if there is a folder called `com.mowglii.ItsycalApp` inside `~/Library/Containers`? (A quick way to open that folder is to type the following into Terminal.app: `open ~/Library/Containers`.) If it is there, can you delete it and see if that helps?

**Comment by jareha** [comment]
Slow loading/displaying may be the wrong explanation. On first run, the app would show in Activity Monitor but not in the menu bar. It would then display in the menu bar when I attempted to open  the app again, having not quit the app after first load.

In either case, the app now appears in the menu bar (immediately) every time I open it, even after quitting the app.

My home computer (the older one) prompted for a password, as I intentionally allow my user account limited privileges. My work computer (the newer one) did not prompt for a password, as my user account has admin privileges.

There is no `com.mowglii.ItsycalApp` folder inside `~/Library/Containers`.

**Comment by pskowronek** [comment]
@sfsam, unable to try it out since the download link is not accessible anymore :/

**Comment by sfsam** [comment]
Version 0.11.1 lets you set an arbitrary datetime pattern and hide the rectangular part of the icon.
