### ISSUE TITLE
Change to non-monospace font for time display

### ISSUE THREAD

**Issue by Jendker** [sfsam/Itsycal#135]
Is there any way to remove the monospace font and switch to normal one? Because if we have e.g. 11 it looks quite bad.
![Ohne Titel](https://user-images.githubusercontent.com/14967831/59857998-5f8ed480-937a-11e9-9c1d-3340520b9038.png)

I tried playing a bit with the code, but I am having problems to go around the issues with signing the app as I don't know much about MacOS development...

I would be very happy if we could change somehow the font, so that the time would be more pleasant to read! I have seen in the commits there was already an approach to disable monospace font, when the seconds are not displayed, but right now for some reason, monospace is always used.

**Comment by sfsam** [comment]
Signing issues can be a pain, but yes, you can change your version of the app to use proportional fonts. I think you can just comment out the 3 lines starting here: https://github.com/sfsam/Itsycal/blob/cec89a11d864589f8aea68ede161caec88ef6ebc/Itsycal/ViewController.m#L389

For now, I'm leaving it this way in the app though.

**Comment by sfsam** [comment]
Hmm, maybe you can just turn off code signing since this is just a build for yourself.

**Comment by Jendker** [comment]
Thank you for your time, that solved it. The time looks much better now!

I somehow managed to change the code signing after creating Apple developer ID.
