### ISSUE TITLE
Feature Request: Week Numbers Option in Calendar View

### ISSUE THREAD

**Issue by aboy021** [sfsam/Itsycal#140]
It would be great if there were an option to display week numbers on the left of the calendar view. Google Calendar has an option like this named "Show week numbers".

Great app by the way, thank you.

**Comment by sfsam** [comment]
You can do this. In Preferences/Appearance you can toggle week numbers. You can also use the 'w' key to toggle them. The website (mowglii.com/itsycal) has this and other keyboard shortcuts as well.
