### ISSUE TITLE
Event on specific day pop up when switch windows

### ISSUE THREAD

**Issue by truongnmt** [sfsam/Itsycal#141]
I often find a weird bug that when switching windows, application, desktop and hover mouse below the Itsycal menu icon, even on specific day pop up, as if I'm hovering on calendar.

![Sep-02-2019 17-02-54](https://user-images.githubusercontent.com/11817656/64099353-0abd0080-cda4-11e9-9817-4ba0c4eff39e.gif)

**Comment by sfsam** [comment]
Can you tell me what version of Itsycal you are running?

**Comment by truongnmt** [comment]
Oh I check for update and just updated to 0.11.17.
Will check if this behavior occurs.
