### ISSUE TITLE
Bad encoding from google calendar

### ISSUE THREAD

**Issue by ademaro** [sfsam/Itsycal#143]
in description broken encoding: https://yadi.sk/i/aJ07nz01Kzrxfw

**Comment by sfsam** [comment]
Could you try updating to the latest version and see if it persists? This issue was hopefully fixed a couple versions ago. Under the gear icon there is a menu with an option to check for software updates.

**Comment by sfsam** [comment]
Is this still an issue?

**Comment by sfsam** [comment]
I believe this was fixed but will re-open if it is still an issue.
