### ISSUE TITLE
Text is not aligned vertically anymore

### ISSUE THREAD

**Issue by Jendker** [sfsam/Itsycal#145]
As mentioned in the other issue https://github.com/sfsam/Itsycal/issues/144 the text is not aligned vertically anymore. Please have a look on the drawing with the old build:

![Old](https://user-images.githubusercontent.com/14967831/65535491-cedc0d80-df01-11e9-9fa6-62fbb23c3c11.png)

And new build
![New](https://user-images.githubusercontent.com/14967831/65535501-d3a0c180-df01-11e9-860b-377997b3bcd6.png)

It is just a couple of pixel difference, but is noticeable.

**Comment by sfsam** [comment]
Thanks for noticing this. 

This is a bug in macOS 10.14+. No change was made to how the text is drawn in Itsycal. 

The change that causes this behavior was setting the Deployment Target of the app to macOS 10.14 from macOS 10.12. This change was made to utilize new API related to Mojave's Dark Mode.

For some reason, changing the deployment target to 10.14 slightly changed the metrics of many UI elements throughout the app. This shouldn't happen. I got most of them, but missed this one.

I have a hack/workaround which I'm hoping I will be able to share fairly soon.

**Comment by Jendker** [comment]
Nice, thanks a lot! I'll close this issue as soon as I can confirm the improvement.

**Comment by sfsam** [comment]
Can you tell me what version of macOS you are running and whether you have a Retina or non-Retina monitor?

**Comment by Jendker** [comment]
I am running MacOS 10.14.6 and the screenshots above are from non-retina screen.
On the retina Macbook display it looks better though. There the text is only slightly too high:

<img width="166" alt="Bildschirmfoto 2019-09-25 um 00 31 16" src="https://user-images.githubusercontent.com/14967831/65555138-f942c080-df2b-11e9-8708-167a857c9db8.png">

**Comment by sfsam** [comment]
I have made a test version. Could you try it out?

https://itsycal.s3.amazonaws.com/Itsycal-0.12.1-test-1.zip

**Comment by Jendker** [comment]
Now it is much better! On the same hight as the original Apple clock in menu bar. I checked it on both screen, retina and non-retina.

Thanks! Closing the issue.
