### ISSUE TITLE
Github landing page could be improved

### ISSUE THREAD

**Issue by xor-gate** [sfsam/Itsycal#149]
It would be nice to convert the landing page to a README.md and add a note about installing it on mac using homebrew `brew cask install itsycal` (see https://brew.sh/). Style can be something like https://github.com/xor-gate/sshfp

Relates to #123

**Comment by sfsam** [comment]
I appreciate the suggestion, but I prefer the README the way it is. It's really cool that someone has made a homebrew recipe for Itsycal, but I'm going to leave it off the README since I have no control over it. I'm just going to keep it simple for now.
