### ISSUE TITLE
[Bug] Tries to open unavailable network drive

### ISSUE THREAD

**Issue by kahluagenie** [sfsam/Itsycal#15]
Trying out the app for the first time and it's awesome! Thanks for making this!

I have a shared network drive added in "Login Items" for my account so it connects on startup every time. Whenever I'm away from home and start up the laptop, it gives me an error message about not being able to connect, which is fine. 

The weird thing though is when I try to open Itsycal preferences, it opens it, but that shared drive connect error pops up right away and closes the Preferences window in the process. I had to remove the shared drive from my Login Items in order to access the preferences.

Stock install of the app. Could be something with it scanning the Login Items for "Launch at Login" option?

OS X 10.11.4

Cheers

**Comment by sfsam** [comment]
Hi,
Sorry it has taken a while to follow up on this. Can you tell me exactly what the error message is? I run Itsycal on my local machine from /Applications and don't have a NAS so I'm not familiar with this setup. Any info you can provide would be helpful. I had one other user email me that he got an error saying his NAS shared folder was not available when trying to open Preferences.

**Comment by kahluagenie** [comment]
Sure! I'll be quite busy the next couple of days and will barely be home (that's where my NAS is), so just give me a a few days to reproduce the issue and I'll get back to you :)

**Comment by kahluagenie** [comment]
@sfsam hey, sorry, I completely forgot to get back to you! Check out this screenshot. This is the message I get when trying to open Preferences in Itsycal while the NAS is in my Login Items.

![screenshot 2016-09-01 16 18 43](https://cloud.githubusercontent.com/assets/2401116/18187634/0e0ff746-7060-11e6-8553-d1419954d916.png)

**Comment by kahluagenie** [comment]
I should note, this is a generic OS X message. That's what I always get when logging into my laptop while away from home.

**Comment by grinser** [comment]
Having the exact same issue here, using macOS Sierra GM - everytime I want to go to preferences I will get this message.

However when I invoke the "search for update" function after trying to go to preferences, it shows the update dialog as well as the preferences window.

**Comment by sfsam** [comment]
@kahluagenie @grinser I don't have access to a network drive, so I can't reproduce this one myself. My current guess is that @kahluagenie is on the right track in suggesting it might have something to do with checking Itsycal's login item status. Can either of you compile your own copy of Itsycal to see if this is the case? The line in question is 198 of PrefsViewController.m:

`_login.state = [self isLoginItemEnabled] ? NSOnState : NSOffState;`

This line checks if Itsycal is in the list of login items and sets the checkmark state accordingly in the UI. Could you comment this line out and see if you still get this behavior? That would at least narrow it down to the reason for the dialog box.

**Comment by kahluagenie** [comment]
Is there an easy way to run in "local" mode? I've never developed apps for Mac, or have used Xcode for that matter :)

When trying to build the project, I get:
No signing certificate "Developer ID Application" found:  No "Developer ID Application" signing certificate matching team ID "<removed>" with a private key was found.

(Removed team ID from the message just in case)

**Comment by sfsam** [comment]
@kahluagenie Wow, you are brave trying this without using Xcode before. You've also encountered "Signing Hell" which is a right-of-passage for all macOS/iOS developers. Bravo.

Try enabling the "Automatically manage signing" checkbox for both the **_Itsycal_** and **_ItsycalMenuExtra_** targets. You choose the targets with a dropdown menu in the upper left corner:

![screen shot 2016-09-15 at 6 16 32 pm](https://cloud.githubusercontent.com/assets/118104/18572525/105e83ca-7b71-11e6-9a7a-7aebe21663b3.png)

You'll also want to comment out one more line to do testing: Line 47 of AppDelegate.swift which enforces Itsycal being run from /Applications. This isn't the case when you are running from Xcode.

**Comment by kahluagenie** [comment]
Ha! Well you did all the work of including Xcode config files in, so my job was easy @sfsam 

So I tried your suggestions, but upon enabling automatic signing, I get two errors

> None of your accounts are a member of 'removed':  An unexpected error occurred. Xcode cannot find a team matching 'removed'.
> No signing certificate "Mac Development" found:  No "Mac Development" signing certificate matching team ID "removed" with a private key was found.

I removed team ID from the above messages.

When I try switching the team to "None" on both targets, I get

> Signing for "ItsycalExtra" requires a development team. Select a development team in the project editor.

Let me know if you have any suggestions!

**Comment by kahluagenie** [comment]
Yeeeah, I figured as much, but was trying to avoid registering hehe.

**Comment by grinser** [comment]
I'm also not a Mac dev but I have an alternative suggestion: 
Could you compile a build with that change and share a dropbox (or something) download link to it?

**Comment by sfsam** [comment]
@grinser @kahluagenie Sorry I dropped the beat on this. I've built a new version with a bunch of changes. One of them is a different way to do the 'launch at login' behavior. If you're still following this issue, you can try it out and see if you still get the same network drive behavior.

https://s3.amazonaws.com/itsycal/Itsycal-2017-01-21.zip

Please let me know if you do try this version out. Also, please make sure this test version is the only version of Itsycal on your system and that it is running from /Applications on your computer.

**Comment by kahluagenie** [comment]
@sfsam Thanks for following up on this! Unfortunately I gave my NAS to my parents and it will probably be a while until I get one for myself again (not a priority right now), so I can't test it at the moment.

**Comment by sfsam** [comment]
@kahluagenie No problem. For what it is worth, someone recently emailed me with this same problem. I pointed them to the test version and they tried it and said it works. So maybe your theory that it had to do with the 'launch at login' feature was right.

**Comment by kahluagenie** [comment]
Right on, great to hear that it works! :)

**Comment by sfsam** [comment]
Version 0.11.1 adds a hidden preference that will disable checking for the login item's status when you open the Preferences window. To use it, type the following in Terminal.app:

`defaults write com.mowglii.ItsycalApp DoNotCheckLoginItemStatus 1`

To stop using it:

`defaults delete com.mowglii.ItsycalApp DoNotCheckLoginItemStatus`

When using this option, you won't see the 'Launch at login' checkbox in Preferences, but whatever your setting is will still be valid. You can still see/set it in System Preferences > Users & Groups > Login Items.

**Comment by kahluagenie** [comment]
Nice! I totally forgot I still had the drive listed under my login items even though I don't have the NAS itself anymore. So I could've tested the version you linked above. Oh well...

Anyway, I just tested and it works great! Error went away as soon as I added the option you specified. Thanks for following up on this @sfsam

**Comment by sfsam** [comment]
@kahluagenie Thanks to you for figuring out the source of the bug. I don't know how long it would have taken me to make the connection. I was pretty stumped.
