### ISSUE TITLE
Can't change time when adding an event on the fly (?)

### ISSUE THREAD

**Issue by MannyV** [sfsam/Itsycal#156]
Hi - this seems stupid but when I click on a day to add an event, I can't change the time, it's greyed out! Do I really have to open the calendar app for this or... what am I missing?

Thanks for an awesome app!
<img width="554" alt="Capture d’écran 2020-02-07 à 11 20 58" src="https://user-images.githubusercontent.com/3706738/74046255-37e98c80-499c-11ea-9ced-fe4634ad4487.png">

**Comment by sfsam** [comment]
Can you please clarify your question? From your screenshot it looks like the time set for the new event is 12:00-13:00, but those numbers don't look greyed out. If you click on the times you should be able to change them.

**Comment by espen** [comment]
I think this is due to the date/time input being displayed more like text than input.

**Comment by MannyV** [comment]
Thanks for the answer. Yes - not only the time is displayed like text, but as far as I understand it _is_ text.

When I click on the +, the above tooltip is displayed, as expected. I can name my event and add a location, but I *can't* change the time of the day, which is automatically set to the present time (on my screenshot above, 12:00 to 13:00 - I can't change that).

Any idea why?

**Comment by espen** [comment]
@MannyV did you try to click the time and enter a new time with your keyboard or are you just using the mouse? It is not a dropdown like other calendar applications show.

**Comment by MannyV** [comment]
I did now - resoved!
