### ISSUE TITLE
Feature Request: Close Itsycal when clicking outside of it

### ISSUE THREAD

**Issue by green-plastic** [sfsam/Itsycal#16]
It currently just stays open no matter what. It'd be nice if I clicked anywhere else and it just closed.

**Comment by resuna** [comment]
Seems like this has actually been implemented, because that's the current behavior. I'd kind of like the old behavior back as an option. ^^

**Comment by green-plastic** [comment]
I just realized after reading your comment @resuna that there is a pin icon to pin Itsycal. I turned pinning off and it does what I want.

**Comment by resuna** [comment]
Thanks, I didn't notice the pin icon either.

**Comment by green-plastic** [comment]
To be fair, it's a small icon and doesn't look like a pin at first glance.
