### ISSUE TITLE
Event added to Google Calendar with a .ics file from an Android phone not showing up in Itsyncal

### ISSUE THREAD

**Issue by tddschn** [sfsam/Itsycal#165]
So I downloaded the file `event.ics` from https://www.apple.com/v/apple-events/home/k/built/assets/event.ics (that's the download link from https://www.apple.com/apple-events/) and opened it with Google Calendar on an Android phone. 

The event was synced to Calendar.app on my Mac, shown as a Google Calendar event, but it's not showing up in Itsyncal after the event was added and synced to the Mac for ~5 days. Tried to restart the app but still couldn't see the event.

Itsyncal version: 0.12.3
macOS version: 10.15.7
Android version: 11

**Comment by sfsam** [comment]
I just downloaded and added the event to my Mac Calendar and can immediately see it in Itsycal. Do you have the calendar selected in Itsycal's preferences?

**Comment by tddschn** [comment]
I added the event from my android phone's google calendar :)

**Comment by sfsam** [comment]
Itsycal is a companion to the Mac Calendar.app. If you can see an event in the Mac Calendar, as long as it isn't in a delegate calendar, it should be visible in Itsycal. But first you have to go into Itsycal's preferences and select which calendars to show. Have you done that?

**Comment by tddschn** [comment]
Thank you for the quick reply!

Yes, I can see the event in Mac's Calendar.app.

Itsycal is configured to show my google calendar event, other events from gcal are shown on Itsycal.

From my experience, 
- Adding ics file to mac calendar app works (event syncs and shown on Itsycal) (tried that once)
- Adding ics file to android's google calendar app doesn't work (event syncs but not shown on Itsycal)  (tried that once too)

**Comment by tddschn** [comment]
Maybe it's some bug not related to Itsyncal, but I don't know how to test it at the moment. :)

**Comment by tddschn** [comment]
I found out why - it was because I added the event to another Google account in the Google calendar 😂
