### ISSUE TITLE
[Feature Request] Calendar Widget in Big Sur

### ISSUE THREAD

**Issue by specter78** [sfsam/Itsycal#167]
In Big Sur, hiding date and time is not possible (AFAIK). So using Itsycal is not worth it.

So what I would like to request is monthly calendar widget that can be added in notification bar.

**Comment by sfsam** [comment]
In Big Sur, you cannot completely hide the system clock. But you can customize it so that it doesn't show the date and takes minimal space to show the time. You can even have it show a tiny analog clock icon if you prefer having date and time together in Itsycal.

**Comment by specter78** [comment]
> But you can customize it so that it doesn't show the date and takes minimal space to show the time.

Considering already limited space in menu bar, it doesn't make sense to use both. So I requested for an Itsycal widget.

**Comment by motte** [comment]
Just so people know, you can significantly reduce the space of the system date menu bar in System Preferences -> Dock & Menu Bar -> Clock

<img width="670" alt="Screen Shot 2020-12-01 at 11 58 30 PM" src="https://user-images.githubusercontent.com/3143788/100844861-3e685980-3431-11eb-8dd8-8ce3a7f60ebd.png">

**Comment by fuzzy76** [comment]
> Considering already limited space in menu bar, it doesn't make sense to use both.

Consider me senseless then. I'm on Catalina and I use Itsycal with date, and the system clock with just the time.

**Comment by markushopkins** [comment]
Until this feature request is processed, a workaround is available. [This answer](url) (relating to Big Sur only) at superuser to a question about adding a full size calendar to the Notification Center provides the steps (and a helpful screenshot of what it looks like):

> On macOS Big Sur, the new design of the Up Next widget can now show a full calendar on M size.

> Go to Notification Center by clicking on the Day time button on the Menu bar, click Edit Widgets and choose Up Next, choose size M and click the + icon. 

Hope this helps!

**Comment by sfsam** [comment]
As @markushopkins has pointed out, Big Sur already provides an Up Next widget as well as a Calendar widget. I'm not planning on making a widget.
