### ISSUE TITLE
someone is selling your calendar app via the AppStore

### ISSUE THREAD

**Issue by ggiessen** [sfsam/Itsycal#17]
Not sure if you are aware that your app is sold in the AppStore. It's called 'SmalCal' by Damian Plak...

**Comment by eirnym** [comment]
This calendar is under MIT licence formally

**Comment by sfsam** [comment]
Thank you for pointing this out. It's unfortunate, but there isn't much I can do. Too bad for people who pay this guy for something they can get for free.

**Comment by mika76** [comment]
You might be able to - copyright and license are two different things, and you own the copyright (at least of the files that he has not modified) - https://www.smashingmagazine.com/2011/06/understanding-copyright-and-licenses/#what-is-a-license

If I was you I'd put in the claim at https://www.apple.com/legal/internet-services/itunes/appstorenotices/#?lang=en and then place the app for sale yourself. No reason why it can't be sold on the marketplace and open source on it's own website. Lots of apps of this.
