### ISSUE TITLE
Menubar not clickable at top most point

### ISSUE THREAD

**Issue by uloco** [sfsam/Itsycal#171]
This issue is only present since Big Sur, I am on 11.0.1

![itsycal-top-bug](https://user-images.githubusercontent.com/8818340/101461900-cec80200-393b-11eb-9e82-29e620e6c89b.gif)

**Comment by pakerwreah** [comment]
This is weird... I'm also on Big Sur 11.0.1 and I don't have this issue.
Have you tried killing and reopening the app? restarting your mac? 
I know this is very dumb but it helps us to make sure it's not a random bug with the OS.

**Comment by uloco** [comment]
I have this issue since the day I updated to Big Sur, which was shortly after it got released to the public (so no beta etc.)

**Comment by uloco** [comment]
What I found out also: The bottom part behaves the same (blinking) when you click inside the bottom most.

**Comment by pakerwreah** [comment]
shit! this is the weirdest bug ever... 
It only occurs if you use the trackpad and you click pressing it down. 
If you click with a mouse or just touch the trackpad, everything is fine 😟

**Comment by sfsam** [comment]
@pakerwreah 🤯 How did you figure this out?
