### ISSUE TITLE
Itsycal does not sync newly created/cancelled meetings

### ISSUE THREAD

**Issue by sidharthyatish** [sfsam/Itsycal#174]
Any newly created events/ meetings are not reflected in itsycal. Mostly results in me missing the meetings. More over, cancelled meetings are not removed from the itsycal list

**Comment by sidharthyatish** [comment]
This problem seems to be widely associated with the system calendar itself rather than itsycal. Thus closing this issue

**Comment by greenmang0** [comment]
@sidharthyatish any possible fix?

**Comment by greenmang0** [comment]
Nevermind, Re-synced Mac Calendar!

**Comment by greenmang0** [comment]
> @sidharthyatish any possible fix?

Nevermind, Re-synced Mac Calendar!
