### ISSUE TITLE
Open meetings without browser page?

### ISSUE THREAD

**Issue by fuzzy76** [sfsam/Itsycal#175]
Just wanted to mention that https://github.com/leits/MeetingBar can open meetings without jumping through the browser. Is this something you could implement? I guess it means assuming clients are installed where applicable.

**Comment by wenlzhang** [comment]
Was going to ask about this too. The menubar given by the calendar app Fantastical is also able to join Zoom meetings without opening the web page. One can click the Zoom icon and join the meeting directly from the installed Zoom app.

**Comment by fuzzy76** [comment]
Great for those with Zoom. Should I open a separate issue for Teams?

**Comment by sfsam** [comment]
Yes please
