### ISSUE TITLE
Open Teams meetings without browser

### ISSUE THREAD

**Issue by fuzzy76** [sfsam/Itsycal#178]
Basically the same as #175, but for Teams.

**Comment by sfsam** [comment]
Do you know the URL scheme for teams video and how that translates to the app URI scheme? Seeing some example URLs and how they translate to the app URI would be helpful since I don't use Teams and don't really know anything about it.

**Comment by fuzzy76** [comment]
I was hoping you'd be able to read it straight out of meetingbar's sourcecode, but I have to admit I couldn't. Granted, I'm not an Obj-C/Swift developer.

But according to https://techcommunity.microsoft.com/t5/microsoft-teams/is-there-a-way-to-launch-ms-teams-meeting-always-in-desktop-app/m-p/511394 you just replace https:// with msteams:// and it should work. Seems to do so here.

**Comment by sfsam** [comment]
I have a test version. Could you please try it and let me know if it works?
http://itsycal.s3.amazonaws.com/Itsycal-msteams.zip

**Comment by fuzzy76** [comment]
Tested both with Teams running, and with Teams not running. It worked great in both cases! :)

**Comment by AliYusuf95** [comment]
I have an issue as stated here https://github.com/leits/MeetingBar/issues/62#issuecomment-724107493, I use Outlook and every link arrives changed to a **Safe Link** which doesn't match the string used to detect zoom meeting.

https://github.com/sfsam/Itsycal/blob/ca8ce3739f651c4558d3c02bbc8a0b03a97ecc16/Itsycal/EventCenter.m#L368

example of safe link URL: 
```url
https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fus02web.zoom.us%2Fj%2F000000000&data=xxxx
```

It needs to split URL params, take `url` query param and decode it to get the real link.

**Comment by sfsam** [comment]
@AliYusuf95 I'm going to close this issue now since it is about Teams meetings without a browser. Could you please create a separate issue for safe links URLs? Thank you.
