### ISSUE TITLE
menu bar item not clickable at very top edge of screen

### ISSUE THREAD

**Issue by felixradtke** [sfsam/Itsycal#179]
This seems to be related to macOS Big Sur, Bartender has recently fixed the very same problem. 

Reproduction:
- Run Itsycal 0.12.5 on any macOS Big Sur workspace
- Try to open the calendar via the menu bar by clicking it at the top edge of the screen. This also applies to the bottom edge of the menu bar.
-> Icon gets highlighted but the calendar does not open.

**Comment by sfsam** [comment]
Thanks. This was reported in issue #171 a little while ago and was fixed. It will be out in the next release.

**Comment by felixradtke** [comment]
Thanks, sorry that I have missed that issue.

**Comment by sfsam** [comment]
I appreciate all bug reports, even duplicates. Thanks for reporting.

**Comment by felixradtke** [comment]
Works now on 0.12.6. However, there is a small cosmetic flaw: When clicked on, I would expect the icon to stay "selected", as it happens with the standard icons such as sound and battery.

**Comment by sfsam** [comment]
I believe it works as expected now. It doesn't stay highlighted on purpose. At the moment, I'm not planning on changing that. Thanks again for the bug report and follow-up testing.
