### ISSUE TITLE
Feature Request: Icon as text matching the time

### ISSUE THREAD

**Issue by ianobermiller** [sfsam/Itsycal#18]
I'm using ItsyCal to replace the "Day, Month Date" portion of the time in the menu bar. It would be awesome if the style could match the time text. I may take a crack at this at some point, so I'm also creating this issue to remind myself!

![image](https://cloud.githubusercontent.com/assets/897931/15690730/c82864f8-2739-11e6-8cc0-6ee203310f61.png)

**Comment by sfsam** [comment]
Version 0.11.1 lets you set an arbitrary datetime pattern and hide the rectangular part of the icon.
