### ISSUE TITLE
Tomorrow section is showing 00:00 for multi-day events

### ISSUE THREAD

**Issue by pakerwreah** [sfsam/Itsycal#180]
<img width="179" alt="Screen Shot 2020-12-23 at 10 48 15" src="https://user-images.githubusercontent.com/803954/103001967-cd3a3480-450c-11eb-9b63-a75db16f7949.png">

**Comment by pakerwreah** [comment]
We could also hide the years when both dates are inside the current one, and also hide the times if both are 00:00.

**Comment by pakerwreah** [comment]
This fixes the "issue" (maybe this behavior was intentional 🤔)
But the `else if (info.isEndDate == YES)` is not working at all for me.
It seems that the endDate of my event is on the next day, because it's a full day event, so this 
`info.isEndDate   = ([_cal isDate:date inSameDayAsDate:event.endDate]` 
doesn't work.

<img width="1025" alt="Screen Shot 2020-12-23 at 12 25 59" src="https://user-images.githubusercontent.com/803954/103012314-2ceb0c80-451a-11eb-8ec3-b990e72f14cb.png">

**Comment by sfsam** [comment]
@pakerwreah Thanks. I will take a look, but I'm a bit busy around the holiday so it might take me a little while. I wish I had commented my code more since date computations are always trickier than they look...

**Comment by sfsam** [comment]
@pakerwreah Can you tell me how to reproduce this? I created an all-day event starting tomorrow that spans 2 days, but it doesn't show 00:00 like in your screenshot.

<img width="552" alt="Screen Shot 2021-06-15 at 10 29 08 PM" src="https://user-images.githubusercontent.com/118104/122162938-3bf7ab00-ce29-11eb-8f94-5a403e7b900f.png">

**Comment by pakerwreah** [comment]
@sfsam Apparently it's Google's fault 🤦🏻‍♂️ 
If you create a regular event it works as expected, but if you create an `Out of office` event we have this issue.
Even though the app and the website say that it is indeed an `All-day` event, you can clearly see that it's different.

<img width="451" alt="normal-event" src="https://user-images.githubusercontent.com/803954/122242356-a2b4ad00-ce99-11eb-95cf-bd215ed03520.png">
<img width="452" alt="out-of-office" src="https://user-images.githubusercontent.com/803954/122242350-a1838000-ce99-11eb-8122-21b0264b803d.png">

Itsycal also thinks my events (even the normal one) ends in Jun 18, which is not true.

<img width="471" alt="normal-details" src="https://user-images.githubusercontent.com/803954/122243506-8d8c4e00-ce9a-11eb-841a-cdec8bb2db07.png">
<img width="472" alt="ooo-details" src="https://user-images.githubusercontent.com/803954/122243510-8e24e480-ce9a-11eb-97b0-867ecd405c14.png">
<img width="200" alt="ooo-end-date-00-00" src="https://user-images.githubusercontent.com/803954/122243515-8ebd7b00-ce9a-11eb-9363-dfd7e06364b3.png">

**Comment by sfsam** [comment]
@pakerwreah I'm not sure what to do about the Google issue. I will fix the way the end date for real all-day events is reported in the popover. I have a special case for single-day all-day events, but it should be generalized for spanning all-day events as well.

**Comment by pakerwreah** [comment]
If that helps, in my `Calendr` project I check if the event starts & ends at midnight, subtract 1 second from the end date and hide the time. That way I've solved these two issues.

**Comment by sfsam** [comment]
I think 18fd946ad246e5b08f26b144e7cdcbd0b31c8ad5 and 04ecaf51af9741737b4229d911bd8db9262d01ae address these issues. For midnight events, instead of making them all-day events, I'm treating them as normal events, but handling the display of duration a bit better. I believe this treatment is more consistent with how other Calendar apps do it.
