### ISSUE TITLE
[Feature Request] Build Universal Binary for Intel and Arm64

### ISSUE THREAD

**Issue by jbernosky** [sfsam/Itsycal#182]
Build a release version for Intel 64-bit and Arm64 architectures.

**Comment by sfsam** [comment]
Workin' on it... https://www.mowglii.com/2021/06/08/apple-silicon-beta.html

**Comment by callahad** [comment]
Appears to be good; update to b2 worked seamlessly, all features seem to work.

**Comment by jbernosky** [comment]
> Appears to be good; update to b2 worked seamlessly, all features seem to work.

Same feedback. Works flawlessly as far as I can tell. No issues with CPU or RAM usage

<img width="978" alt="Screen Shot 2021-06-17 at 11 35 26 AM" src="https://user-images.githubusercontent.com/50927894/122428731-2df87600-cf60-11eb-94d0-0458e4ffb8bf.png">

**Comment by sfsam** [comment]
Thanks for your help.
