### ISSUE TITLE
Calendar weeks do not match unicode week numbers

### ISSUE THREAD

**Issue by jimcasey** [sfsam/Itsycal#183]
Hello!

I use a custom date format (`yyyy.ww`) to show the year/week of the year in the toolbar, and then have the _Show calendar weeks_ option checked in settings:
<img width="246" alt="Screen Shot 2021-01-20 at 5 56 13 PM" src="https://user-images.githubusercontent.com/1511191/105259370-e274a400-5b48-11eb-8103-8bf55567ea1e.png">

It appears the weeks listed in the calendar are not aligned with the value displayed in the titlebar – notice in the screenshot here, it is currently week 4 in the titlebar but week 3 in the calendar:
<img width="211" alt="Screen Shot 2021-01-20 at 5 53 15 PM" src="https://user-images.githubusercontent.com/1511191/105259754-9d9d3d00-5b49-11eb-90f3-7545179f209e.png">

I realize that there are competing standards – for example, the calendar follows [F.4 of the Unicode standard linked in the docs](http://unicode.org/reports/tr35/tr35-25.html#Date_Format_Patterns), while the titlebar calculation follows the "1/1 is always week 1" rule, which is the same as Outlook (and my organization, and thus my preference 😄).

Any thoughts on what it might take to make this consistent?

**Comment by sfsam** [comment]
Thanks for posting this issue. I wrote about it here: https://twitter.com/mowgliiapps/status/1347305213397327873?s=21
Basically, you can set the macos calendar to use the ISO standard.

**Comment by djeikyb** [comment]
To save a click, itsycal does not support the gregorian calendar. Only the iso 8601 standard is supported by itsycal. Macs configured for usamerican english default to the gregorian calendar. There are subtle differences, and week year number is one of them.
<img width="669" alt="image" src="https://user-images.githubusercontent.com/794743/129821454-cc93df71-6c1b-4d6a-96d7-0f5960107a46.png">
