### ISSUE TITLE
Any plans to add apple silicon native support?

### ISSUE THREAD

**Issue by h4n0** [sfsam/Itsycal#189]
Just searched through the issue list and haven't found any arm-arch / apple silicon related discussion. 

Are we planning to do so? If not yet, I can try to do it as I have a Macbook Pro with m1 processor.

I'm C++ programmer but still new to Objective C. My understanding is to add some extra arm compiling flags in project config file and that should do the trick, is it like this? If so, I would like to do this voluntarily.

**Comment by sfsam** [comment]
Yes. https://www.mowglii.com/2021/06/08/apple-silicon-beta.html

**Comment by sfsam** [comment]
The latest version (0.13.0) supports Apple Silicon.
