### ISSUE TITLE
[Feature Request] Separate UI treatment depending on a meeting state

### ISSUE THREAD

**Issue by rafiron** [sfsam/Itsycal#190]
Hi,

In the mac calendar app, one can clearly see the meeting that is marked as 'maybe' from the accepted meetings. 

It would be very useful if there would have been a way to quickly identify in itsycal meeting list the state of any meeting - accepted, maybe or not accepted.

**Comment by sfsam** [comment]
Could you provide a screenshot of how participation status is displayed in Calendar.app or some other app? I don't use this feature myself so I don't know what it looks like. Currently, Itsycal does not display events that the user declined.

**Comment by rafiron** [comment]
You can refer this screenshot. The meeting which is accepted comes with a solid color while the meeting which is marked as 'maybe' is coming with a pattern.
A meeting whose status has not been marked maybe shown without a solid color (to differentiate from the one where the meeting invite was accepted)

<img width="1200" alt="Screenshot 2021-06-22 at 1 34 41 PM" src="https://user-images.githubusercontent.com/24583737/122887861-e8bcb580-d35e-11eb-871f-d68182520ed2.png">

**Comment by sfsam** [comment]
I'm thinking of something like this to visually indicate meeting status:

<img width="214" alt="Screen Shot 2021-06-25 at 8 29 43 AM" src="https://user-images.githubusercontent.com/118104/123448289-9c0bf100-d58f-11eb-8d4f-0ba5f6ab3e3e.png">

**Comment by rafiron** [comment]
Hi @sfsam ,

Thanks for taking my suggestion. This looks really nice 🙌🏻

I had a minor suggestion for improvement. In the current design, between `Tentative` and `Accepted` it's a bit hard to differentiate (the only difference being the bullet being solid or not which is a bit hard to notice at a quick glance).  

I was thinking about whether if we can add an outline or gradient of sorts in the `Tentative` to differentiate it clearly from the other 2 states (like we added a different UI behavior for `Pending`). Not sure how the UI might look in that scenario.

**Comment by sfsam** [comment]
I'll think about it. FWIW, this is how Calendar.app shows things in Month-View. I came up with my design before realizing that it's almost the same. I prefer having Pending show the color of the calendar rather than just a gray dot:

<img width="156" alt="Screen Shot 2021-06-25 at 8 51 50 AM" src="https://user-images.githubusercontent.com/118104/123451801-b2677c00-d592-11eb-8e85-3dc7f6d1c659.png">

**Comment by rafiron** [comment]
Yeah, just a gray color will make it difficult to understand for which calendar is this invite pending.

**Comment by sfsam** [comment]
This is in 0.13.1.
