### ISSUE TITLE
Croatian translation

### ISSUE THREAD

**Issue by milotype** [sfsam/Itsycal#191]
If you can and want to, please use my attached Croatian translation. 
The `.xliff` file was easier to translate then the `.strings` files.
I hope that doesn't matter for implementation.

Thank you.

[hr.xliff.zip](https://github.com/sfsam/Itsycal/files/6715844/hr.xliff.zip)

**Comment by sfsam** [comment]
Thank you. I can't support more languages at the moment, but I have tagged this with the 'language' tag for future reference.
