### ISSUE TITLE
Popup becomes stuck and cant close on losing focus - MacOS Big Sur

### ISSUE THREAD

**Issue by spooks7er** [sfsam/Itsycal#195]
On MacOS Big Sur, while the popup is opened from the menu bar, on losing focus it does not hide and is sitting on top the of the other windows.

Only fix is to close the itsical entirely and reopen it.

**Comment by alex-petrea** [comment]
This still happens even after the latest update. 

https://user-images.githubusercontent.com/3057563/162419316-759ba9d2-6fe2-4a71-8da3-dad2a3f3e0b8.mov

**Comment by sfsam** [comment]
@alex-petrea Does this help? https://www.mowglii.com/itsycal/help.html#pin

**Comment by alex-petrea** [comment]
@sfsam that works beautifully. I didn't know this was a feature, it actually makes all the sense in the world. 
Thanks for the help 🫡

**Comment by sfsam** [comment]
@alex-petrea I'm glad that was it. Your screencast was helpful.

**Comment by Alexander-Serov** [comment]
Maybe this issue could be closed? Seems resolved.

**Comment by sfsam** [comment]
I believe this issue was resolved. Please re-open if not.
