### ISSUE TITLE
Is it possible to set the datetime in language other than English?

### ISSUE THREAD

**Issue by anaclumos** [sfsam/Itsycal#197]
I have reviewed the [datetime](https://www.mowglii.com/itsycal/datetime.html) instructions; would there be any way that I can somehow make the DateTime in a different language? I am not sure if this is supported by the Unicode standard

I am looking for something like

```js
'E' == 'Mon' ? '월요일' : 'E' == 'Tue' ? '화요일' : ...
```

Of course, it could be any method, I just want to display the DateTime in different language.

**Comment by sfsam** [comment]
I think if you go to System Preferences > Language & Region and choose Korean or whatever other language you like as your Primary language, it will show that in the menu bar.
<img width="780" alt="Screen Shot 2022-02-02 at 8 42 06 PM" src="https://user-images.githubusercontent.com/118104/152282440-9c4933ca-7ab0-4cc0-9258-43f691bc8d7a.png">

**Comment by anaclumos** [comment]
Can you confirm if this is the only way to do it? I see that Itsycal does not support additional languages, and therefore would not have any effect.

![image](https://user-images.githubusercontent.com/31657298/152447555-35e19dd4-eb93-4764-8684-b67bb1da257a.png)

**Comment by sfsam** [comment]
I'm not sure what you're looking at, but the menu bar date/time is drawn by macOS, not Itsycal. So it can show whatever language macOS supports. The date and time translations within Itsycal work this way too. It's just the UI elements where I had to provide translations that are limited to certain languages.

**Comment by anaclumos** [comment]
@sfsam, Got it. Thank you so much for your help. Closing this issue.
