### ISSUE TITLE
[FEATURE] Let the user choose the default calendar for adding events

### ISSUE THREAD

**Issue by klauslanza** [sfsam/Itsycal#2]
Lot of times I personally add an event just to find out later that it's on a differnet calendar of my personal one. 
As an alternative to settings, it would be great just to remeber the last selection also.

**Comment by sfsam** [comment]
Thanks for the feature request.

Itsycal is a companion to the Mac Calendar.app and as such uses the same default calendar as the one set up in Calendar.app's preferences. If you want a different default calendar for Itsycal, you can set it in Calendar.app's prefs.

I can see the appeal of having the calendar change, but I think the current behavior is more consistent for most people and it is how Calendar.app works.
