### ISSUE TITLE
Multiple months

### ISSUE THREAD

**Issue by mika76** [sfsam/Itsycal#20]
It would be awesome to be able to show multiple months in the popup, not just the one. Sometimes when planning a trip it helps to see two or even three months at the same time. How about an option. The popup could even show a full year if you want, myself I would love 2 months 😊

**Comment by darko20** [comment]
+1 This would be a super-useful feature.

**Comment by mika76** [comment]
![bagheera](https://cloud.githubusercontent.com/assets/229311/23124873/74ff75f8-f76f-11e6-8d5d-8a42644dbe98.jpg)

Bagheera says you should do this one next 😜

**Comment by sfsam** [comment]
In 0.11.2 you can drag the calendar down or press control-j to see more rows. Drag up or press control-k to see fewer rows.
![feb-25-2017 10-27-17](https://cloud.githubusercontent.com/assets/118104/23337892/584baa22-fbb0-11e6-867b-6bcb0c0d5e2a.gif)

**Comment by mika76** [comment]
Brilliant - it's awesome. Thanks a lot!

**Comment by darko20** [comment]
Great! Has that version been released?

**Comment by sfsam** [comment]
@darko20 Yes. It should update soon or you can manually check for updates.

**Comment by darko20** [comment]
I did the manual check for updates but it says the old version is the
current version.

**Comment by sfsam** [comment]
@darko20 Which version do you have?

**Comment by darko20** [comment]
0.10.16 - I knew I should have included it in my previous email but I was
overcome with laziness.

**Comment by sfsam** [comment]
@darko20 That's the last version that runs on macOS 10.10 and 10.11. The 0.11.x versions of Itsycal require macOS 10.12. If you have macOS 10.12, I don't know why it isn't updating but you can just download it from the website.

**Comment by darko20** [comment]
My joy has turned to disappointment, I'm indeed running running 10.11,

**Comment by sfsam** [comment]
@darko20 :(

**Comment by darko20** [comment]
What's the feature that depends on 10.12?

**Comment by sfsam** [comment]
@darko20 I actually don't remember right now. But that's the point. It simplifies the code and process for me a lot and I don't have to keep track of old API. Every year Apple changes stuff and I (all Mac developers, really) have to work hard just to stay in place.

**Comment by darko20** [comment]
Understandable. I'll just build a version that doesn't have that constraint
and hope it does crash...
