### ISSUE TITLE
Keep the meeting icon active even for past events

### ISSUE THREAD

**Issue by iliocatallo** [sfsam/Itsycal#201]
Hello there!

At present, Itsycal disables the meeting button for past events. It would be handy to keep the button active instead; that would make it possible to join a common room from some recurring event (in my specific instance, joining the common team room from the daily standup event).

Thank you,
ciao!

**Comment by sfsam** [comment]
Thanks for the suggestion. This was added in version 0.13.3. From the release notes:

> A new hidden preference lets you have meeting buttons enabled indefinitely once they are turned on. By default, meeting buttons turn on 15 minutes before the meeting start time and turn off at the end of the meeting. This pref keeps them on indefinitely so you can easily revisit, say, a common room. To use it, open Terminal.app and enter `defaults write com.mowglii.ItsycalApp EnableMeetingButtonIndefinitely 1`. To turn it off, change the `1` to a `0`.
