### ISSUE TITLE
Menu bar item is not aligned vertically in macOS 12.4

### ISSUE THREAD

**Issue by jaklan** [sfsam/Itsycal#206]
After upgrading to macOS Monterey 12.4, the icon is not aligned vertically anymore:
<img width="196" alt="image" src="https://user-images.githubusercontent.com/24907857/181010190-a6ebd65e-e0cd-4ac1-bd65-1be2a19bc788.png">

It's even better visible when you highlight it:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/24907857/181009766-d688509a-e834-4981-8466-8f4291ccc178.png">

**Comment by sfsam** [comment]
Could you provide these screenshots showing the whole length of the menu bar? I don't have macOS 12. Thanks.

**Comment by jaklan** [comment]
@sfsam here you go, disabled TopNotch to make it more visible:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/24907857/181028074-bec70537-cb8e-4d58-84d7-ef85e54aaac9.png">

**Comment by jaklan** [comment]
Also the close view without TopNotch:
<img width="194" alt="image" src="https://user-images.githubusercontent.com/24907857/181028739-ff8266d0-074f-41ed-9b03-74dff1af4c3e.png">

**Comment by sfsam** [comment]
Thanks.

**Comment by sfsam** [comment]
Does the latest release resolve this issue? There is also a new hidden preference with which you can adjust the baseline if you'd like something different. https://www.mowglii.com/itsycal/versionhistory.html

**Comment by jaklan** [comment]
Yes, thanks!
