### ISSUE TITLE
dark skin option

### ISSUE THREAD

**Issue by neonfrontier** [sfsam/Itsycal#21]
This is great, any option for a dark skin coming up?

P.S: Command + drag can move any icon in the task bar now, so you can remove that note from the webpage. :)

**Comment by briantully** [comment]
+1

**Comment by Fastidious** [comment]
I consider all "me too" to be on the inconsequential realm, but this request would make Itsycal so aesthetically gorgeous! Please consider it.

**Comment by Antairez** [comment]
+1

Loved the app by the way.

**Comment by ABeltramo** [comment]
I'm working on it. Any graphic advice on color scheme? How about somenthing like this?
<img width="199" alt="schermata 2017-06-08 alle 15 51 26" src="https://user-images.githubusercontent.com/1122217/26932292-683a2126-4c63-11e7-9b9d-85ffae6be315.png">
I'm no Photoshop expert.. 😆

**Comment by briantully** [comment]
Looks great! Will the background also have some alpha transparency like standard menu items do?

**Comment by suhodolskiy** [comment]
I hope to see this option ever 😃 
https://dribbble.com/shots/3535605-Mac-Statusbar-Calendar-App

![cal_2x-2](https://user-images.githubusercontent.com/8992530/26946407-ced9a6ca-4c97-11e7-9b52-3df722d0beb7.png)

**Comment by ABeltramo** [comment]
Wow amazing! I'll try to make it look just like this!

**Comment by ABeltramo** [comment]
My progress so far:
<img width="233" alt="schermata 2017-06-09 alle 11 55 00" src="https://user-images.githubusercontent.com/1122217/26970676-81a1b9d8-4d0a-11e7-802d-ed7108c753bc.png">
<img width="233" alt="schermata 2017-06-09 alle 11 54 30" src="https://user-images.githubusercontent.com/1122217/26970680-8423b576-4d0a-11e7-8dc0-8194e26022a5.png">
It uses the vibrant OSX style and is semitransparent. It's a graphical huge change what do you think @sfsam?

**Comment by sfsam** [comment]
@ABeltramo It's funny. When I was working on this I ended up in almost exactly the same place with mockups that look practically identical to yours. At first I thought it looked really clean because of the elimination of "unnecessary" lines. But I used it for a while and found that I missed those lines. Itsycal is a _glanceable_ calendar and without the lines my eyes have to do a lot more work to parse what I'm seeing. It resulted in a loss of utility. It was an interesting experience.

But I think it's on the right track. I also used the vibrant dark so that it harmonizes with the rest of the system. It needs (at least some of) the lines back. Maybe without the shadow in the dark mode.

**Comment by Fastidious** [comment]
@sfsam I find the one linked above ([and here](https://dribbble.com/shots/3535605-Mac-Statusbar-Calendar-App)) to be very good.

**Comment by ABeltramo** [comment]
I think the only solution here is to make a theme choser. Default, vibrant light and vibrant dark. This way we also could open up to new color theme. What do you think @sfsam?

**Comment by sfsam** [comment]
@ABeltramo In January I added the tabbed preferences panel with the Appearance tab. Part of the reason for doing that was to make a place for an eventual popup menu to choose between a default or dark theme.

**Comment by ABeltramo** [comment]
Created the pull request. Aside from the few issues left the code is ready and this is the final result
![themes](https://user-images.githubusercontent.com/1122217/27036971-ddb9b6ac-4f86-11e7-9598-affd1c739c7a.jpg)
And from now on it's really easy to create new themes! 🎉

**Comment by sfsam** [comment]
I've uploaded a version with light and dark themes to test:

https://s3.amazonaws.com/itsycal/Itsycal-themes-beta.zip

![themes](https://user-images.githubusercontent.com/118104/27068451-0cade1fc-4fc5-11e7-8f43-a547fd8e23f6.png)

**Comment by sfsam** [comment]
@ABeltramo It looks like we were working in parallel. :)

**Comment by sfsam** [comment]
Version 0.11.4 introduced a dark theme option.

**Comment by Fastidious** [comment]
Can that scroll/line on the right be made dark too? It looks rather weird, don't you agree?

![screen shot 2017-07-09 at 19 21 41](https://user-images.githubusercontent.com/8352292/27998372-f89e9676-64db-11e7-89cd-3697573db4ad.png)

**Comment by sfsam** [comment]
@Fastidious For now, you can get rid of it by going to System Preferences... > General and choose "Automatically based on mouse or trackpad" under "Show scroll bars".

**Comment by Fastidious** [comment]
That is what I have:

![screen shot 2017-07-10 at 06 36 55](https://user-images.githubusercontent.com/8352292/28014321-39c07dfa-653a-11e7-9980-3257fd1d9015.png)

**Comment by sfsam** [comment]
@Fastidious Interesting. I have a workaround for the next update. It appears to be a known issue that the system doesn't respect the background color when legacy (non-overlay) scrollbars are turned on. Just curious, what kind of input device are you using? Do all your windows have scrollbars?

**Comment by Fastidious** [comment]
@sfsam I am using a regular mouse/keyboard (non “magic”). I have scrollbars, when there is something to scroll.

**Comment by sfsam** [comment]
@Fastidious Is this working better now (0.11.5)?

**Comment by Fastidious** [comment]
@sfsam just updated. It is! No more white scrollbars, thanks!
