### ISSUE TITLE
Menu bar string doesn't update

### ISSUE THREAD

**Issue by ajsirota** [sfsam/Itsycal#215]
(followup from #214)

It seems like the custom data in the menu bar doesn't update as often as it should: 
<img width="396" alt="image" src="https://user-images.githubusercontent.com/67526318/209042506-4bcfad6d-f4c7-4094-a1c2-340c6d4bf94e.png">
Is this expected? Is there a setting I'm missing to make it update faster?

**Comment by sfsam** [comment]
It should update in sync with the clock. Can you share a screenshot of the Preference panel where you put in the date-time pattern?

**Comment by sfsam** [comment]
MM is months. mm is minutes. MM is giving you 12 because it is December. The page I linked above links to all the date time patterns.
