### ISSUE TITLE
Feature request - black on white menu item, to match the rest of the menu bar.

### ISSUE THREAD

**Issue by resuna** [sfsam/Itsycal#22]
First, thank you for producing this and releasing the source on Github. Three cheers and a tiger.

Second, the black-outlined menu item is cool and all, but it stands out a bit much. An option to invert it (or, as may be, un-invert it ^^) and scale the font up in the process would not go amiss.

**Comment by sfsam** [comment]
This isn't quite the same, but version 0.11.0 adds the option for an outlined icon (instead of the standard solid one) and this stands out less, particularly when the dark menu bar is used.
