### ISSUE TITLE
why my cal the custom date display error

### ISSUE THREAD

**Issue by xiaodiao1212** [sfsam/Itsycal#220]
<img width="206" alt="image" src="https://user-images.githubusercontent.com/14543505/217457824-0d4d77dd-14ee-4afc-a655-6566e100a54e.png">

here is my setting

<img width="236" alt="image" src="https://user-images.githubusercontent.com/14543505/217457948-48e9d384-6e25-4887-91dd-c03d4e63f479.png">

**Comment by xiaodiao1212** [comment]
sorry forget write my version。
here is

<img width="218" alt="image" src="https://user-images.githubusercontent.com/14543505/217458296-426834d2-aac4-4d56-9f1a-21e54629b91a.png">

**Comment by sfsam** [comment]
Try d instead of D.

**Comment by xiaodiao1212** [comment]
oh thanks, it is fixed.
