### ISSUE TITLE
Itsycal opened and nothing shows.

### ISSUE THREAD

**Issue by ladyrick** [sfsam/Itsycal#228]
When I open Itsycal, there is nothing shows in status bar and on desktop. Nothing happened.
But Itsycal process is really there and not crashed.
<img width="559" alt="image" src="https://github.com/sfsam/Itsycal/assets/10379994/8f78a236-8980-4d89-ad06-6297867b8499">

**Comment by ladyrick** [comment]
I finally find the problem. It is because my M1 mac's NORTH occupied the space on status bar. I remove all the icons and Itsycal shows.

**Comment by nk9** [comment]
Sounds like this can be closed.
