### ISSUE TITLE
Support for extended monitors

### ISSUE THREAD

**Issue by sambhav-gore** [sfsam/Itsycal#23]
If I click on the icon in the menu bar on an extended monitor (additional screen), the calendar drop down still shows on the main laptop screen. 

Add support for multiple screens please.

**Comment by sfsam** [comment]
@sambhav-gore I've attempted to fix this. Could you try it out and let me know if it works?

https://s3.amazonaws.com/itsycal/Itsycal-2017-02-13.zip

**Comment by sfsam** [comment]
I believe this is fixed in 0.11.2.
