### ISSUE TITLE
Losing settings on MacOS shutdown or restart

### ISSUE THREAD

**Issue by ncasdpo** [sfsam/Itsycal#236]
I have an M1 MacBook. All Itsycal appearance settings are lost on a restart.

This is what my Itsycal calendar normally looks like:

<img width="266" alt="Screenshot 2023-12-13 at 19 52 13" src="https://github.com/sfsam/Itsycal/assets/153771236/c9a380f9-d8e1-4854-8f95-48ca5175f225">

Below is what it looks like after MacBook restarts after a shutdown.  Appearance settings that have been lost include font size, menu bar icon styling and the show month/day of week in icon settings.

<img width="207" alt="Screenshot 2023-12-13 at 19 54 55" src="https://github.com/sfsam/Itsycal/assets/153771236/e871e852-dc07-4d2c-8447-2007f2419e66">

**Comment by ncasdpo** [comment]
@sfsam Just bumping in case you haven't seen this. I keep having to re-change appearance settings on every restart, don't know if this is something you are seeing on your own machine?

**Comment by sfsam** [comment]
@ncasdpo I'm afraid I cannot replicate this. Itsycal doesn't do anything special for its settings. It uses the standard Mac [User Defaults](https://developer.apple.com/documentation/foundation/nsuserdefaults) system to store these values. The Mac usually stores these settings under `~/Library/Preferences`. For Itsycal specifically, the file would be `~/Library/Preferences/com.mowglii.ItsycalApp.plist`. Can you see that file on your system?

**Comment by ncasdpo** [comment]
@sfsam This is fixed now, thank you for your help. `~/Library/Preferences/com.mowglii.ItsycalApp.plist` was an empty file, so I uninstalled Itsycal & then deleted the file (previously an uninstall of Itsycal by itself hadn't solved the problem). After reinstall, settings are no longer lost on restart
