### ISSUE TITLE
DoNotDrawOutlineAroundCurrentMonth borks UI on application startup

### ISSUE THREAD

**Issue by GreyAsteroid** [sfsam/Itsycal#246]
Having DoNotDrawOutlineAroundCurrentMonth set when starting Itsycal causes it to fail loading any UI when clicking on the menu bar item. This behavior occurs regardless of what DoNotDrawOutlineAroundCurrentMonth is set to as long as the key exists.

**Comment by sfsam** [comment]
Thanks for the report. Can you describe exactly how I can reproduce this? I set DoNotDrawOutlineAroundCurrentMonth to 1, quit Itsycal, and then relaunched it, and it works for me. I also unset it (so it still exists, but is zero) and quit/relaunched and that works too.

**Comment by GreyAsteroid** [comment]
> Thanks for the report. Can you describe exactly how I can reproduce this? I set DoNotDrawOutlineAroundCurrentMonth to 1, quit Itsycal, and then relaunched it, and it works for me. I also unset it (so it still exists, but is zero) and quit/relaunched and that works too.

Here's a screen recording of the issue
https://drive.google.com/file/d/1BbrO2wExP6g00kIdolHQ1lvMNPJ4SNnP/view?usp=sharing

**Comment by sfsam** [comment]
Hmm, even after watching the screencast, I can't reproduce this either with or without the key. Is the console output relevant?

Can you try the command this way instead:
`defaults write com.mowglii.ItsycalApp DoNotDrawOutlineAroundCurrentMonth -bool YES`

**Comment by sfsam** [comment]
Hmm, even after watching the screencast I can't reproduce this. Is the console output relevant?

Can you try the command this way?
`defaults write com.mowglii.ItsycalApp DoNotDrawOutlineAroundCurrentMonth -bool YES`

**Comment by GreyAsteroid** [comment]
> Hmm, even after watching the screencast I can't reproduce this. Is the console output relevant?
> 
> Can you try the command this way? `defaults write com.mowglii.ItsycalApp DoNotDrawOutlineAroundCurrentMonth -bool YES`

I captured the console output for good measure, but it turns out using an actual bool seems to prevent this issue from happening.

I don't know if it matters enough to modify the code to account for this or just adjust the update notes to use a bool instead of 0/1 for the command.

**Comment by sfsam** [comment]
Thanks. I've updated the notes. I'm curious, can you tell me what version of macOS you are on?

**Comment by GreyAsteroid** [comment]
> Thanks. I've updated the notes. I'm curious, can you tell me what version of macOS you are on?

Nothing special, latest Sonoma (14.5). It does look a bit different though because I have reduce transparency enabled and I'm using a non-retina display.

**Comment by sfsam** [comment]
How interesting. I'm on latest Sonoma (14.5) as well. This issue reminded me of a past one where similar behavior was happening on an older macOS, so I had guessed that was the issue here too. But nope. 

Thanks for surfacing this.
