### ISSUE TITLE
Remove Border Around Menu Bar Icon

### ISSUE THREAD

**Issue by kr-younghoon** [sfsam/Itsycal#247]
Hello,

First, I want to thank you for creating Itsycal. It's a fantastic tool that I use every day.

![image](https://github.com/sfsam/Itsycal/assets/126774519/accb5396-d775-4d64-be5d-127b4a46b3ca)

I have a suggestion regarding the menu bar icon. Currently, there is a border around the icon, as shown in the attached screenshot. I believe the icon would look cleaner and more integrated without this border.

Could you please consider adding an option to remove the border or changing the default icon to be borderless?

Thank you for your attention and for your great work on Itsycal.

**Comment by evanre** [comment]
@kr-younghoon you can use any date pattern and disable the icon, and thus it'll display the date without a border.
![CleanShot 2024-09-23 at 02 05 51@2x](https://github.com/user-attachments/assets/5ce03dc9-9407-4b20-81ff-9874e5efe248)
![CleanShot 2024-09-23 at 02 06 04@2x](https://github.com/user-attachments/assets/1a0ab4b6-2657-4197-b5c3-c708d3d7591f)
