### ISSUE TITLE
Change Itsycal shown like Day-O

### ISSUE THREAD

**Issue by EddieChen12** [sfsam/Itsycal#25]
Hi sfsam.
Itsycal is a great app. I'm like it. But it can't show time.
I'm just change menu icon display like calendar icon, date text, day of week and time. It's seens like OS X base information.
It can perfect replace Day-O now.

link:
https://github.com/EddieChen12/Itsycal

preview:
![image](https://github.com/EddieChen12/Itsycal/raw/master/preview.png)![image](https://github.com/EddieChen12/Itsycal/raw/master/preference.png)

**Comment by gerardp** [comment]
Great! Thanks EddieChen12

**Comment by gerardp** [comment]
One feature request:
Can you make the month view a plain version? get rid off the borders, something like Day-0
Thanks !

![img](https://cloud.githubusercontent.com/assets/168353/18726897/c16787f0-8046-11e6-8765-3d88d43f451d.png)

**Comment by EddieChen12** [comment]
Do you mean like this Day view?
http://ww4.sinaimg.cn/large/72f96cbajw1f827f7maopj20py05qabb.jpg

**Comment by gerardp** [comment]
Yes, something like that this will be perfect.

![captura de pantalla 2016-09-22 a las 9 44 19](https://cloud.githubusercontent.com/assets/168353/18740283/36cc92b2-80a9-11e6-9db9-b1f1d150b17f.png)

**Comment by EddieChen12** [comment]
I'm make a plain version, this is a snapshot.
![image](http://ww1.sinaimg.cn/large/006y8lVagw1f83lhtlloyj305l07tq3m.jpg)

**Comment by gerardp** [comment]
Great, good job.
Thanks EddieChen12

**Comment by pskowronek** [comment]
I've applied this enhancement on my forked itsycal and it works as a charm - finally a date/time menubar app with calendar which suits me.
Two thumbs up to include this extension in the next release :)

**Comment by EddieChen12** [comment]
Im glad you like them.

**Comment by JohnDCCIU** [comment]
Adding my vote for adding the time (with ability to display in various formats).  With that, I can use itsycal to finally replace the old MenuCalendarClock abandonware.

Not sure if this should be another enhancement request, but I'm not a big fan of spelling out the month, which seems to be itsycal's only way of displaying it; I'd like to be able to control itsycal's menuitem display with a custom date string (which can include the time), much as MenuCalendarClock allowed:

<img width="446" alt="clockcontrol" src="https://cloud.githubusercontent.com/assets/839598/19900228/238a4c8a-a039-11e6-9fa3-648ddc103155.png">

**Comment by gerardp** [comment]
@JohnDCCIU 
No, there is a new version:
http://shauninman.com/archive/2016/10/20/day_o_2_mac_menu_bar_clock

**Comment by sfsam** [comment]
What is the advantage of combining the clock with the date? As it is, you can have both displayed in the menu bar. And because menu bar items can be arranged, you can even put them side-by-side. I understand that some people want to format things in very specific ways, but beyond formatting what is the advantage?

**Comment by danielcompton** [comment]
Formatting, and the spacing between the system date and Itsycal doesn't look great.

**Comment by pskowronek** [comment]
> What is the advantage of combining the clock with the date?

1. the original OSX time is useless for daily work, having date + time combo is a simple solution - no matter where you click whether it is date or time you have this precious calendar view
2. combined date & time saves space on menubar and looks much better
3. having an option to configure whether to show time or not gives people a choice to use system time or not, this can be turned off by default if you like
4. already having the time patch available you risk the project be forked to include this option, I think it is more sensible to have just one trusted origin of this app

**Comment by sfsam** [comment]
I made a test version of Itsycal that has a clock. It's a "hidden" feature - you activate it by modifying Itsycal's preferences via the command line. For example:

`defaults write com.mowglii.ItsycalApp ClockFormat "H:mm"`

To disable the clock, either set ClockFormat to "" or delete it altogether:

`defaults write com.mowglii.ItsycalApp ClockFormat ""`

`defaults delete com.mowglii.ItsycalApp ClockFormat`

NB:
- The smallest unit supported is seconds.
- This version requires macOS 10.12+.
- There's a new preference for an outlined icon which may look better with a dark menu bar.
- I'm still not sure about this feature.

Please let me know what you think or if/when you find bugs:
https://s3.amazonaws.com/itsycal/Itsycal-clock.zip

**Comment by pskowronek** [comment]
Works for me. Thanks for this release. I hope that this time option will be configurable via UI soon.

**Comment by sfsam** [comment]
Version 0.11.0 gives the option for a clock.
