### ISSUE TITLE
Adding new all-day event with alert of "1 week before" causes strange alert times in official Calendar apps

### ISSUE THREAD

**Issue by edelstone** [sfsam/Itsycal#250]
I noticed a small "bug" where the alert that appears in the Mac and iOS Calendar apps differs slightly than the alert specified in the Itsycal event creation interface.

## Steps to reproduce:
1. Create a new event in Itsycal.
2. Select "All-day".
3. Set the alert to "1 week before".
4. Save the event.
5. Open the Mac Calendar app or iOS Calendar app and look at the alert time. For Mac Calendar app the alert is set to a custom alert of "8 days before at 12AM", and for the iOS Calendar app the alert is set to a custom alert of "7 days before (12AM)".

For the record, I don't see this discrepancy when choosing other all-day alert times. Let me know if I can provide any more details.

## Itsycal setup
![363529863-35cecbde-8f24-4d8d-96ca-a623f2ab8472](https://github.com/user-attachments/assets/b30af013-4a3e-4efd-b647-ffc763455ea3)

## Mac Calendar app
![363529920-20bd8835-25dc-49dd-979d-10abfefb215f](https://github.com/user-attachments/assets/e418f2b4-fa5a-4c73-8880-9f282af9879f)

## iOS Calendar app
![363529932-6e303e45-0c4b-4457-9660-5200636c83cc](https://github.com/user-attachments/assets/9684bc9e-be5c-42f2-8b10-9ee82f0d1b6a)

**Comment by edelstone** [comment]
@sfsam I tested this locally, and it appears that the math in the file `EventViewController.m` relating to the "1 week before" interval is slightly off. Currently the value is `-604800` but I think `-572400` is more accurate.

`(32400 – (86400 x 7)) = -572400`

**Comment by sfsam** [comment]
@edelstone I reproduced this behavior as you described. I also tested your fix and it worked on both iOS and macOS. Thank you!
It sounds like you are able to compile your own copy of Itsycal with this fix?

**Comment by edelstone** [comment]
@sfsam Yes, though once I found the fix I switched back to the official app since the bug doesn't impact me too much. I assume you'll implement the fix with your next release?

**Comment by sfsam** [comment]
Yes.

**Comment by edelstone** [comment]
Awesome, thank you!
