### ISSUE TITLE
Itsycal won't close when clicking outside its dropdown pane

### ISSUE THREAD

**Issue by silverfoxdoc** [sfsam/Itsycal#254]
Absolutely love the application and it's just what I was looking for but there is one thing which I am not sure whether it's a bug or by design. 

After opening the Itsycal dropdown pane by clicking on it in the menu bar, if you then click anywhere on the screen, which is not the dropdown pane of Itsycal, it does not close; you can only close it by clicking on Itsycal date in the menu bar itself. 

It's always been like this since as far as I can remember whilst using for the last couple of years, on both MacOS sonoma and now sequoia.

**Comment by edelstone** [comment]
@silverfoxdoc Do you have it "pinned" by any chance? There is a way to toggle this behavior.

![Screenshot_2024-11-10_at_7_18_50 AM](https://github.com/user-attachments/assets/a297f19f-fea1-4ecc-8365-91120499748f)

**Comment by silverfoxdoc** [comment]
thank you, I didn't realised that is what that icon did. Now I see it is actually in the help section of your website too :man_facepalming:

**Comment by edelstone** [comment]
> thank you, I didn't realised that is what that icon did. Now I see it is actually in the help section of your website too 🤦‍♂️

No worries. The docs have pretty much everything covered, including all the keyboard shortcuts. And to be fair I'm just an user of Itsycal, it's not my software. cheers
