### ISSUE TITLE
Itsycal, macOS 10.12 Sierra and Move to App folder

### ISSUE THREAD

**Issue by ivan98** [sfsam/Itsycal#27]
I downloaded latest Itsycal (0.10.14) and installed with the following procedure:

    cd /Applications
    sudo unzip ~/Downloads/Itsycal.zip

I tried various ways to invoke the application, all fails with the message:

    Move Itsycal to the Applications folder
    Itsycal must be run from the Applications folder in order to work properly.
    Please quit Itsycal, move it to the Applications folder and relaunch.

I tried from Terminal, open /Applications/Itsycal.app
I tried double clicking it from Finder
I tried spotlight search

**Comment by sfsam** [comment]
@ivan98 I can reproduce this, but I don't know why it is happening. It will work if you unzip Itsycal.zip by double-clicking on the zip file in ~/Downloads and then drag Itsycal.app to /Applications.

**Comment by ivan98** [comment]
@sfsam Yes, your method works. I'm more of a CLI guy, so unless I see a .DMG, and especially when I see a .ZIP, I usually approach it from a Terminal. Thanks, I will close this.

**Comment by matt-bailey** [comment]
I've just tried using Itsycal and I'm having the same issue. Here are the steps I took to 'install' it:

- Double clicked on the ZIP file in the Downloads folder
- Dragged the app to the ~/Applications folder
- Double clicked on the app to open it

I'm on Mac OS 10.12.6.

**Comment by matt-bailey** [comment]
I've just re-downloaded the ZIP file and now it installs fine. Very strange...

**Comment by coolswitcher** [comment]
Oops, I did it again)
<img width="598" alt="screenshot 2017-11-01 17 53 59" src="https://user-images.githubusercontent.com/646663/32280836-2873d09e-bf2e-11e7-98db-1915b0b3fb77.png">
macOS High Sierra 10.13.1
