### ISSUE TITLE
version 0.10.15 is broken on OSX 10.11

### ISSUE THREAD

**Issue by madushan1000** [sfsam/Itsycal#31]
Date label does not show up in the menu bar. The process is still running though.

**Comment by pakerwreah** [comment]
-[__NSCFLocale countryCode]: unrecognized selector sent to instance 0x7f9f60c25f50

**Comment by jessecarbon** [comment]
Also seeing this on OSX 10.10.5.

**Comment by sfsam** [comment]
Sorry! I pulled 0.10.15 as fast as I could but not fast enough. Can you try 0.10.16? I made a change as described here: [https://www.mowglii.com/itsycal/versionhistory.html](url) which hopefully fixes this.

**Comment by sfsam** [comment]
A number of people have emailed me so I think this issue is resolved with 0.10.16.
