### ISSUE TITLE
display of location

### ISSUE THREAD

**Issue by philippkeller** [sfsam/Itsycal#36]
I like itsycal a lot. Besides Alfred and Bartender it's the only custom app I've installed.

One of the thing that is missing for me is that it doesn't show the location for events.
I use it usually at work and would like to know in which room the next meeting is.

**Comment by sfsam** [comment]
If you hover over the event in the agenda below the calendar, a tooltip will show the event's location.

**Comment by philippkeller** [comment]
indeed it does! Thanks, that solves my use case. 👍  for this very useful app

**Comment by daturkel** [comment]
Is there any plan to add an option for always-displayed location (say, below the event name?). I use itsycal from the keyboard shortcut and hovering is a mouse behavior, which is less convenient.

**Comment by sfsam** [comment]
@daturkel I'll look into it. Thanks for the suggestion.
