### ISSUE TITLE
can't show events list in macOS Sierra

### ISSUE THREAD

**Issue by Angryrou** [sfsam/Itsycal#37]
Hi, I just downloaded it yesterday. Adding events via itsycal is **cool**! However, I can't see the events added on ltsycal bar. So, I also can't delete an events. I don't know if it is caused by the new macOS Sierra I use. BTW, I have chosen the "Events list show" in preferences. Here is the situation, having events in calendar app but not in itsycal bar

![image](https://cloud.githubusercontent.com/assets/8079921/21036095/7d2533da-bdfe-11e6-8237-33492debf103.png)

**Comment by sfsam** [comment]
@Angryrou,
I am running Sierra so I don't think that is the issue. Some questions:
- When you first launched Itsycal, did you give it permission to access your calendars?
- Do you have the calendars you want to see checked off in Itsycal's preferences?
Thanks.

**Comment by Angryrou** [comment]
@sfsam ,
I forgot to check on the categories, seems it is off by default. It works now, THANKS!
