### ISSUE TITLE
Feature request: Disable auto update

### ISSUE THREAD

**Issue by gingerCodeNinja** [sfsam/Itsycal#39]
Is there a way to disable auto update, or disable auto checking for updates?

If not, could you consider building it in?

Love the app, keep up the good work! thankyou!

**Comment by sfsam** [comment]
@gingerCodeNinja Itsycal shouldn't be auto-updating. It does automatically check for updates, but you can choose to skip the update if you don't want it. Overall, there aren't too many updates. I think there were 9 in all of 2016. What would be the reason for disabling checking?

**Comment by gingerCodeNinja** [comment]
I guess I don't want to be prompted as soon as I login about whether to update some app or not, it's the equivalent user experience of a popup on a website. 

I know I might miss out on some fantastic features, or bug fixes, but it's a simple calendar app, the very thing I like about it - if I need something more or encounter a bug, the first thing I'd do is update it.

**Comment by sfsam** [comment]
@gingerCodeNinja Thanks for the reply. I'll add this in the next version.

**Comment by sfsam** [comment]
Version 0.11.1 lets you opt-out of automatically checking for updates. You can still manually check.

**Comment by gingerCodeNinja** [comment]
Perfect, Thanks for adding that!

**Comment by sfsam** [comment]
@gingerCodeNinja Thank you for the suggestion and also for your generosity.
