### ISSUE TITLE
Add support to change weekend days

### ISSUE THREAD

**Issue by sagilo** [sfsam/Itsycal#42]
There is an option to change first day of week, but there isn't one for changing the weekend days (for highlighting).
Here it's Friday / Saturday (and I assume it's the same for whoever uses Sunday as first day of week, but I might be wrong here) 

Thank you very much

**Comment by sfsam** [comment]
@sagilo This can be done already although there isn't yet a proper UI for it. Please see the release notes for version 0.10.16: http://www.mowglii.com/itsycal/versionhistory.html

**Comment by sfsam** [comment]
Version 0.11.1 let's you highlight arbitrary days. You can use this to define 'weekend' any way you like.
