### ISSUE TITLE
Feature request: native look and feel

### ISSUE THREAD

**Issue by maiiku** [sfsam/Itsycal#48]
I have a small feature request: 
I'd like itsycal to have an option to display with same look and feel as built-in date/time menu widget, so that they can be put seamlessly next to each other.

Currently it looks like this:
![image](https://cloud.githubusercontent.com/assets/1031355/22683081/8a256fd6-ed16-11e6-857d-6c2ac531e427.png)

So I guess that would mean removing the border and as much of a right margin as possible.

**Comment by sfsam** [comment]
In 0.11.1 you can mimic the system clock style by using a custom datetime pattern (for example, hh:mm) and hiding the rectangular icon. See Preferences > Appearance.
