### ISSUE TITLE
Icon invisible after 0.10.10 update 

### ISSUE THREAD

**Issue by BenLeggieroNCR** [sfsam/Itsycal#5]
Screenshots say it all:
![Itsycal on a dark menu bar. Popup works, but there is no icon.](https://cloud.githubusercontent.com/assets/10726457/12979871/af4b2152-d0a7-11e5-8027-211bc00e0f6a.png)![Itsycal on a light menu bar. Popup works, but there is no icon.](https://cloud.githubusercontent.com/assets/10726457/12979870/af4a5db2-d0a7-11e5-86b5-c16b7087f784.png)

**Comment by sfsam** [comment]
@BenLeggieroNCR Hi Ben, Do you still have this issue after restarting your machine? If you are on OS X 10.10, you need to either restart or kill the SystemUIServer process because it is caching the old menu extra.

**Comment by BenLeggieroNCR** [comment]
@sfsam I haven't restarted my machine, but i did kill Dock. Killing SystemUIServer did fix this, so that's a viable workaround. Maybe make that a part of the update process?

**Comment by sfsam** [comment]
@BenLeggieroNCR I'm glad it's working now. I put a note in red bold text in the release notes that come up in the Sparkle updater dialog box. I'm not sure what else I can do. I'm going to close this issue since it seems like you have resolved it.
