### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by Fastidious** [sfsam/Itsycal#50]
Running `Check for Updates...` renders:

![screen shot 2017-03-15 at 19 28 04](https://cloud.githubusercontent.com/assets/8352292/23975167/9542477a-09b5-11e7-9090-ef56b103c422.png)

**Comment by sfsam** [comment]
@Fastidious Can you please provide a bit more context? I'm not getting that on my end. That alert is created by the Sparkle updater and unfortunately isn't very descriptive. Does it work when you try again later? If you download Itsycal from the website, do you still get that error?

**Comment by Fastidious** [comment]
It happens over and over. The first thing I did was to download the application from the website, and update. Same happened afterwards. I will try on another machine later tonight and let you know how it goes.

**Comment by sfsam** [comment]
@Fastidious After you downloaded and updated, did that initial update work? Is this the latest version?

**Comment by sfsam** [comment]
@Fastidious Are you still experiencing this? I am still unable to replicate it. Which version are you using?

**Comment by Fastidious** [comment]
@sfsam I am still experiencing this, but only in one machine, so it has to be a local issue. The version I have installed is `0.11.2`. I will fully delete and add again, to see how it goes. Will post back.

**Comment by Fastidious** [comment]
OK, please forgive me, for I acted stupidly for a while. My [Little Snitch](https://www.obdev.at/products/littlesnitch/index.html) had Itsycal blocked from contacting AWS. Removed the rule, and it works fine. Apologies.

**Comment by sfsam** [comment]
@Fastidious No problem, glad you got it working.
