### ISSUE TITLE
Too much spacing between numbers

### ISSUE THREAD

**Issue by mozeryansky** [sfsam/Itsycal#52]
I've uploaded an image showing Itscal on the left and macOS's default date on the right. As you can see the number spacing is is very significant. Can this be changed to match macOS?

<img width="367" alt="screen shot 2017-03-25 at 11 13 49 pm" src="https://cloud.githubusercontent.com/assets/3287719/24329089/ce3b8a20-11b0-11e7-8c01-d377fe627f3d.png">

**Comment by mozeryansky** [comment]
I have fixed this for myself. In case you want to incorperate it as a setting or a hidden user default this is what I did. In ViewController.m::createStatusItem, you change the spacing attributes of the font to be monospace, you have a comment saying "Use monospaced font in case user sets custom clock format". Is this still relevant now that you are using the San Francisco font? For my fix, I just removed those lines and now the font matches exactly the same as macOS.

<img width="367" alt="screen shot 2017-03-25 at 11 13 49 pm" src="https://cloud.githubusercontent.com/assets/3287719/24329208/186bad0c-11b4-11e7-8699-a3ee7d8080ef.png">

**Comment by mozeryansky** [comment]
Also just a tip. When you use a pragma mark, you can have the dash before your title to accomplish the same effect in Xcode's dropdown menu:

```
#pragma mark -
#pragma mark Menubar item
```
is the same as
`#pragma mark - Menubar item`

**Comment by sfsam** [comment]
@mozeryansky If you look in the commit history, you'll see that I've gone back and forth between a monospace and proportional font for the label part of the icon. There's a trade-off. The goal is to not have the changing time affect the width of the status item as each minute passes. This is so your whole status bar (all the items to the left of Itsycal) aren't subtly shifting each minute (or second if your clock is showing seconds). Of course, when the time changes from a single-digit hour to a double-digit hour (or vice versa), there will be a shift.

The system clock achieves this by having a massive amount of padding on the left and right and then custom drawing the datetime centered within the padding. Itsycal does it with normal padding and a monospaced font. Programmatically this solution is much simpler. Interestingly, the system clock also uses a monospace font when you display seconds so Itsycal is matching that without the massive padding. 

I'm going to keep it the way it is for now. A cool thing about open-source is that if you have a strong subjective preference for the proportional font, you can have it.

Thanks for the pragma tip.

**Comment by mozeryansky** [comment]
Yeah thanks, I did fork your project and I'm running my version. I'll just have to upstream your changes over time.

**Comment by gith-account** [comment]
@mozeryansky, this has also been discussed in issue #45 .

**Comment by macbugs** [comment]
> **_The system clock achieves this by having a massive amount of padding on the left and right and then custom drawing the datetime centered within the padding. Itsycal does it with normal padding and a monospaced font._**

It seems like the padding on Itsycal is not symmetrical though....

![padding](https://user-images.githubusercontent.com/101867641/159117700-43cd2659-666f-4ef0-bf44-249312f38cd7.png)

...And could it be reduced ? (as Bartender does, for example):

![Bartender menu bar spacing](https://user-images.githubusercontent.com/101867641/159117837-38aa6dd2-5c54-4a43-ac25-46fdf865269c.png)
