### ISSUE TITLE
First day of the week

### ISSUE THREAD

**Issue by ChainsawBaby** [sfsam/Itsycal#56]
Love the app, only annoyance, is the week starts on Sunday. Where as in Norway, we use Monday as the first day of the week.

Would be awesome to have an option to choose which day of the week you want to be the first

**Comment by suhodolskiy** [comment]
@ChainsawBaby 
<img width="337" alt="screenshot 2017-06-01 13 19 40" src="https://cloud.githubusercontent.com/assets/8992530/26675569/255eb9d4-46cd-11e7-987a-610df37d1b95.png">

**Comment by ChainsawBaby** [comment]
Oh clever me, I was looking for it in Appearance
Cheers @suhodolskiy
