### ISSUE TITLE
MacOS 10.13 High Sierra BETA

### ISSUE THREAD

**Issue by sfsam** [sfsam/Itsycal#57]
Apple just released the first beta of macOS 10.13. For the most part, the current version of Itsycal (0.11.2) seems to work, but there are issues. I will be posting a test version with fixes shortly if you are on the new OS and would be willing to test Itsycal.

**Comment by sfsam** [comment]
I've uploaded a version of Itsycal to test on macOS 10.13 beta.

https://s3.amazonaws.com/itsycal/Itsycal-macOS10_13-beta.zip

**Comment by jbrodley** [comment]
This doesn't seem to have fixed the high power usage that started in High Sierra for me.  I have also now updated to Beta 2.

**Comment by sfsam** [comment]
@jbrodley can you create a new issue for this? I’m not aware of high power usage with high Sierra.

**Comment by jbrodley** [comment]
Done. https://github.com/sfsam/Itsycal/issues/59

**Comment by mrleblanc101** [comment]
Hi, I can't download the macOS 10.13 beta nor the "New look" beta (https://www.mowglii.com/2017/06/13/itsycal-new-look-beta.html)... Is there something I'm missing, do you need to add me to a beta test list ?

**Comment by sfsam** [comment]
@mrleblanc101 Sorry, I took them down and forgot to say anything. The new look was introduced in 0.11.4 and the macOS 10.13 code that was in the beta is now in the current version. Itsycal doesn't officially support 10.13, but as far as I know, it basically works.

**Comment by mrleblanc101** [comment]
Alright, I didn't have a Mac for a few months but I don't really see a difference... That's why I was asking ! And yeah the app should run fine on macOS 10.13 but there is some issues still open about this so I was wondering.
