### ISSUE TITLE
Hide Today's Previous Events

### ISSUE THREAD

**Issue by daturkel** [sfsam/Itsycal#64]
I would love to see an option where today's events _which have already happened_ are not shown. Right now I see all of today's events, even if it's 11:59pm. I'd love to only see the ones that have yet to come. 

Similarly, it would be nice to be able to toggle on or off whether "all-day" events are shown at all.

**Comment by sfsam** [comment]
Version 0.11.6 dims today's events that have already happened so I'm going to call this one done. Thanks for the suggestion.
