### ISSUE TITLE
Blue colour + general UI

### ISSUE THREAD

**Issue by kr15uk** [sfsam/Itsycal#66]
Feature request.
Be able to change blue colour to any other - blue colour for today and navigation.

Also while we're at it... Maybe it's just me but I do find it a bit unpleasant to the eye.
Square around the selected date (the same as blue one) is not in the middle, can't it be centered?!
Light theme is too white, can't it be matched to menu bar grey?! Maybe colour code for custom colour?!

Thanks.

**Comment by sfsam** [comment]
@kr15uk The square around the selected date is centered when you take into account the dot showing an event. Given the size of the calendar, there aren't a lot of pixels to play with.

<img width="74" alt="screen shot 2017-07-18 at 9 29 39 am" src="https://user-images.githubusercontent.com/118104/28328566-d5180266-6b9b-11e7-9b81-87c4a9d970d8.png">
