### ISSUE TITLE
UI redesign

### ISSUE THREAD

**Issue by denbue** [sfsam/Itsycal#67]
First off, great tool. Thanks for open sourcing it – I would like to join. As @kr15uk pointed out in a previous issue (#66), the UI could deserve a little refinement. Below you can find a _first draft_ to gather some feedback. The design follows mostly the same structure and elements.

Since I'm not a obj-c coder myself, the project would obviously depending on your time resources.

![itsycal](https://user-images.githubusercontent.com/2946670/28493036-3aa65404-6f0f-11e7-9bb0-8bba504186ae.jpg)

**Comment by sfsam** [comment]
@denbue Thank you for the suggestion. I'm certainly open to new ideas, but for now I'm happy with the overall design of Itsycal. I do not want to make Itsycal a clone of Fantastical. If people want Fantastical, they should buy it - it is a wonderful app! If you have suggestions on how to tweak the light and dark themes on Itsycal, please let me know.

**Comment by denbue** [comment]
I see your point, thanks for your feedback. Pull request #58 is going into the right direction, by adding more contrast between the sections. Maybe its possible to include some of the suggestions into the light and dark theme.
