### ISSUE TITLE
Do not show the dots under the dates when showing events

### ISSUE THREAD

**Issue by acrostich** [sfsam/Itsycal#69]
Showing events is convenient, but the dots that then appear for all dates with events clutters the calendar display. Either disable completely the dots or make it an option.

(Can't see how to make this an enhancement request and not an issue.)

**Comment by stackptr** [comment]
Never done any macOS development but I kind of want to take a stab at this!

**Comment by acrostich** [comment]
@sfsam has already implemented this enhancement suggestion in a beta he made available in the high energy thread. Thank you for both implementing this and reducing energy consumption of Itsycal.

**Comment by charlottetan** [comment]
might want to close issue if already implemented?

**Comment by sfsam** [comment]
@charlottetan  Right you are. Implemented in Itsycal 0.11.7.
