### ISSUE TITLE
Can't see Outlook/Exchange Calendar

### ISSUE THREAD

**Issue by andyrozman** [sfsam/Itsycal#72]

**Comment by andyrozman** [comment]
Sorry forgot to add details and editing doesn't work...
When I try to configure Calendars (for events), Outlook/Exchange calendar is not given as an option. I have MS Office installed, do I need something else, or is this just missing?

**Comment by sfsam** [comment]
Itsycal shows the calendars you've added to the Mac Calendar.app (not including delegate calendars). It doesn't talk directly to Google or Exchange or anywhere else. Try adding your accounts to the Mac Calendar?

**Comment by andyrozman** [comment]
Thanks that helped. After I added it to Calendar config it was also visible itsycal.

**Comment by dresh** [comment]
> Itsycal shows the calendars you've added to the Mac Calendar.app (not including delegate calendars). It doesn't talk directly to Google or Exchange or anywhere else. Try adding your accounts to the Mac Calendar?

have added the exchange server account in mac calendar, itsycal still doesn't pickup the events from that calendar. have tried restarting itsycal. Doesn't help.

**Comment by sfsam** [comment]
Can you see the calendar listed in Itsycal's preferences? If so, is there a checkmark next to it?
