### ISSUE TITLE
Is it possible to add icon without outline and bigger text?

### ISSUE THREAD

**Issue by Stanko** [sfsam/Itsycal#74]
First, I feel bad requesting feature having couple of open source projects myself. But I have no experience with objective C to do a PR.

Anyway, I would really like to have an option to show only text version of the icon. WIthout borders and background, with a little bit bigger text.

**Why?**

If you check this screenshot, you'll see that `Sat, Oct 7` is smaller and kinda hard to scan visually. 

<img width="400" alt="screenshot 2017-10-07 09 56 04" src="https://user-images.githubusercontent.com/776788/31305949-bfb3c9b6-ab45-11e7-8662-466a70573417.png">

Having it borderless with bigger font would make it easier to read, and it would fit seamlessly with the native clock.

Hopefully this doesn't require too much of your time and effort.

Thank you for the great little app!

**Comment by sfsam** [comment]
You can do this with Itsycal. Go to Preferences > Appearance and use a custom date format. You can click on the **(?)** icon to get some documentation on formats. Once you've entered a custom format, you can select the **Hide icon** checkbox.

For example, try the following format:

`E, MMM d h:mm a`

**Comment by Stanko** [comment]
Thank you very much! I feel a little bit stupid now 🙂 

This is awesome, keep up the good work!
