### ISSUE TITLE
How to change the color used for the datetime in the menu bar ?

### ISSUE THREAD

**Issue by lrhazi** [sfsam/Itsycal#78]
Hello, not sure why the datetime is in black color.. How do I change that?

<img width="415" alt="screen shot 2017-10-16 at 10 46 52 pm" src="https://user-images.githubusercontent.com/120354/31644395-19c29fb0-b2c4-11e7-9a30-79caf7cfbfcf.png">

**Comment by sfsam** [comment]
@lrhazi I haven't seen this before or seen any reports of it. The colors should invert automatically depending on whether or not you are using the dark menu bar and Dock preference in System Preferences. Does restarting Itsycal work?

Can you tell me what OS and version you are using as well as anything else about your setup that you think might be pertinent?

**Comment by lrhazi** [comment]
Oh! that easy! restarting Itsycal fixed it!  Thank you.

macOs 10.12.6, and I do use flux (https://forum.justgetflux.com/category/5/mac-os-x) in case it related.

Thanks a lot.
