### ISSUE TITLE
Chrome blocks itsycal.zip

### ISSUE THREAD

**Issue by seperman** [sfsam/Itsycal#81]
I tried to download itsycal.zip but Chrome blocked the download.
It says: Failed - Blocked.
Chrome on Mac. Version 62.0.3202.75 (Official Build) (64-bit)

**Comment by sfsam** [comment]
Hmm. I haven't seen this before. I just downloaded Itsycal.zip with Chrome. 
Chrome on Mac. Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by sfsam** [comment]
Are you still observing this behavior? I can't reproduce it. Is there any more information in the error you're seeing?

**Comment by seperman** [comment]
Ok turned out uMatrix which is a chrome extension was blocking the s3 bucket. It works now. Sorry for the confusion.
