### ISSUE TITLE
Can't update Istycal

### ISSUE THREAD

**Issue by mozeryansky** [sfsam/Itsycal#82]
After I updated and click relaunch, Istycal says it can't update. I checked Console and this is the error message:

Sparkle: The update archive isn't signed with a DSA key, and the app is signed with a new Code Signing identity that doesn't match code signing of the original app: Error Domain=NSOSStatusErrorDomain Code=-67050 "(null)" UserInfo={SecCSArchitecture=x86_64}. At least one method of signature verification must be valid. The update will be rejected.

**Comment by sfsam** [comment]
Which version did you upgrade from?

**Comment by mozeryansky** [comment]
I currently have 0.11.2

**Comment by sfsam** [comment]
Maybe your version is somehow corrupted? I just downloaded 0.11.2 (and also a few other versions) and was able to run it (as well as the others) and then update to 0.11.8 without incident. 

Could you try that? Remove or rename your current version, download 0.11.2 from the website, move it to the Applications folder and launch it. Check for updates and see if it works.

**Comment by mozeryansky** [comment]
I believe I have installed a version I forked from your source. Ha, I even mentioned needing to upstream your changes in #52. Thanks!
