### ISSUE TITLE
Option for dark/light menu bar icon.

### ISSUE THREAD

**Issue by klonos** [sfsam/Itsycal#83]
It would be great if the dark/light theme would match the menu bar icon (white text over black background / black text over white background). Better yet if this was a separate option, independently from what theme was chosen for the calendar itself.

I have moved the itsycal indicator next to the native Mac OS time/date indicator and t's annoying that they do not match:

<img width="181" alt="screen shot 2017-11-18 at 8 24 40 am" src="https://user-images.githubusercontent.com/2423362/32965000-f763ecfa-cc39-11e7-92ec-0e14d3e5d868.png">

**Comment by sfsam** [comment]
There is an option for an outline icon if you want dark text. You can also set a date/time pattern with the option to entirely hide the icon.
