### ISSUE TITLE
[question] where is the settings file stored?

### ISSUE THREAD

**Issue by nitrocode** [sfsam/Itsycal#84]
Great app by the way! I was curious where the settings were so I can backup my settings using [mackup](https://github.com/lra/mackup).

Thank you!

**Comment by sfsam** [comment]
Itsycal uses the standard Mac defaults system. You can see your settings by opening Terminal.app and typing: `defaults read com.mowglii.ItsycalApp `

**Comment by sfsam** [comment]
I think the mackup config would look like this?

```
[application]
name = Itsycal

[configuration_files]
Library/Preferences/com.mowglii.ItsycalApp.plist
```
