### ISSUE TITLE
Installation error: Move Itsycal to the Applications folder

### ISSUE THREAD

**Issue by suntrop** [sfsam/Itsycal#89]
I have downloaded the app and moved it to /Applications/Itsycal.app but when I open it, I get the error message

```
Move Itsycal to the Applications folder
Itsycal must be run from the Applications folder in order to work properly.

Please quit Itsycal, move it to the Applications folder, and relaunch.

/private/var/folders/hz/61w348dfg75gsd93gg4g09gl9yxxkzvlc0000gn/T/AppTranslocation/4851313D-DEFF-4210-B593-FF4859139C8B/d/Itsycal.app

```
I have no idea why this error comes up.

**Comment by sfsam** [comment]
Try this:
https://www.mowglii.com/itsycal/appfolder.html

**Comment by suntrop** [comment]
Thanks helped!
But I put it manually in the App folder before. Anyhow, it is working now :-) Thanks!

**Comment by sfsam** [comment]
I don't know why it didn't work the first time, but I'm glad you got it working.
