### ISSUE TITLE
Doesn't recognise system time zone changes

### ISSUE THREAD

**Issue by andrewn** [sfsam/Itsycal#93]
I have the "Set time zone automatically using current location" turned on. So when I fly from London to Berlin, the system clock automatically changes to the correct time zone. (System Preferences -> Date & Time -> Time Zone).

Itsycal doesn't detect this change and displays all events in the "old" time zone e.g if I'm in London (UTC+0) an event will display as starting at 3pm. When I go to Berlin (UTC+1), my system clock changes but the event still displays 3pm in Itsycal. After restarting Itsycal, it displays the event time as 4pm, which is correct.

It would be great if Itsycal could detect when the system time zone changes without having to be quit and started again.

**Comment by sfsam** [comment]
Are you running High Sierra? I can reproduce this behavior on High Sierra, but not Sierra.

**Comment by andrewn** [comment]
Yes, I'm running High Sierra 10.13.3.

**Comment by sfsam** [comment]
I think this is a bug in High Sierra. The NSDateIntervalFormatter class seems to cache the date string it produces and doesn't reformat when the timezone changes. This is the framework class used to produce locale-aware time intervals (the duration for events). It works properly in 10.12 and prior. I've submitted a bug report to Apple (rdar://38074488).

Weirdly, NSDateFormatter class (no interval) seems to continue to work properly on High Sierra.

**Comment by andrewn** [comment]
Thank you for looking into this. Hopefully a future version of High Sierra will fix it!

Thanks so much for all your work on Itsycal.

**Comment by sfsam** [comment]
I believe this is working now on 0.11.11.
