### ISSUE TITLE
Add showing time

### ISSUE THREAD

**Issue by kopach** [sfsam/Itsycal#94]
Hi.
Would it be possible to add ability to show time as well as day, month, etc in menubar? Currently, to see time - I need to use native clock. The problem with this approach is that it's take too much space in menubar. And I would like to reduce that space usage. 

![screenshot at 16-02-01](https://user-images.githubusercontent.com/8749624/37213765-456a3640-23b3-11e8-9f0e-89157b5fe943.png)

**Comment by sfsam** [comment]
Itsycal can show the time. In Preferences/Appearance, you can set a custom datetime pattern. For example, "h:mm".

See https://mowglii.com/itsycal/datetime.html for info on patterns.
