### ISSUE TITLE
Feature request: selectable text on event title and locations

### ISSUE THREAD

**Issue by jaredreich** [sfsam/Itsycal#98]
I am often wanting to highlight/select an event's title or location text, in order to copy and paste it elsewhere (google maps, url, etc...).

Thoughts?

Also, thanks for your work on this excellent application!

**Comment by sfsam** [comment]
@jaredreich The latest update lets you copy events with a context menu. Right-click on the event to get the menu.

**Comment by jaredreich** [comment]
@sfsam Thanks for the update, for this though I actually meant when you click on an event, and the popup shows up, all that text in there should be selectable (location, event details, event title, etc.)

**Comment by sfsam** [comment]
The copy menu should pick up all those items (title, loc...)

**Comment by jaredreich** [comment]
Right, I suppose it does, but it's all concatenated together which isn't really useful, e.g.:
`Some Event Name Some Event Location/Link Jun 18, 2018, 10:30 – 11 AM`

**Comment by sfsam** [comment]
That's surprising. The code inserts newlines and I get them when I copy and paste:
<img width="199" alt="screen shot 2018-06-18 at 11 56 16 am" src="https://user-images.githubusercontent.com/118104/41556119-a6be9c94-72ee-11e8-9082-8fb584165f30.png">

**Comment by sfsam** [comment]
I might be able to make the lines individually selectable. They are in different cells so you wouldn't be able to select all of them with the mouse, but you could just select the title or location or duration. If you wanted all, the menu item would still do that.

**Comment by jaredreich** [comment]
I think what you're describing is exactly what I'm after - imagine you have an event with a location that you want to copy, to paste somewhere else, the ideal steps would be:
- click itsycal menu bar icon
- click event to show popup
- select text of location (or title or description or whatever)
- either CMD+C or right click and select "Copy"

If each line is only individually selectable, I'd say that's totally fine!

**Comment by sfsam** [comment]
It'll be in the next update.

**Comment by jaredreich** [comment]
You're awesome. Once again, many thanks for your work on this awesome project.

**Comment by sfsam** [comment]
I believe this is working now in 0.11.11.

**Comment by jaredreich** [comment]
Yes! Just tried it out and it works as expected, well done sir and thank you!

**Comment by sfsam** [comment]
Thank you for the suggestion.
